### ISSUE TITLE
Bind numpad (or other keys) using blight:bind

### ISSUE THREAD

**Issue by ryanmichaelsmith** [Blightmud/Blightmud#101]
It would be great to be able to bind numpad (application keys) using blight:bind. Perhaps by allowing us to provide an ASCII sequence for the first argument. I use numpad for movement when mudding and other repetitive commands.

**Comment by LiquidityC** [comment]
This one might be solvable once #128 is in. I can't test because I don't have a numpad.

**Comment by chosig** [comment]
This should be closed, works after #128 was implemented.

**Comment by LiquidityC** [comment]
Hey @chosig ! Thanks for confirming this. I will close.
