### ISSUE TITLE
Error when installing Nix package on ARM64 darwin

### ISSUE THREAD

**Issue by erratic-pattern** [Blightmud/Blightmud#1069]
Hey there. Not sure if I should submit an issue here or in nixpkgs, but I encountered an error when trying to build blightmud on a Macbook Pro M3 using home-manager and nix-darwin.

## Configuration

Configuration is just a basic home-manager module that looks like this:

```
{ pkgs, ... }: {
  home.packages = with pkgs; [
    blightmud
  ];
}
```

Here is a [git branch](https://github.com/erratic-pattern/nix-config/blob/blightmud-error/home/mud/client.nix) with the full nix flake configuration for my setup.

## Error message

```
error: builder for '/nix/store/d2is2kbs43ykmzhw0b8pqr9nnhsrfp1q-tinyfugue-50b8.drv' failed with exit code 2;
       last 25 log lines:
       > # define dmalloc(md, size, file, line)  mmalloc(md, size)
       >                                         ^
       > ./malloc.h:37:29: note: expanded from macro 'mmalloc'
       > # define mmalloc(md, size)              malloc(size)
       >                                         ^
       > malloc.c:54:21: error: call to undeclared library function 'realloc' with type 'void *(void *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       >     memory = (void*)drealloc(md, ptr, size, file, line);
       >                     ^
       > ./malloc.h:64:6: note: expanded from macro 'drealloc'
       >                                         mrealloc(md, (void*)(ptr), (size))
       >                                         ^
       > ./malloc.h:39:34: note: expanded from macro 'mrealloc'
       > # define mrealloc(md, ptr, size)        realloc(ptr, size)
       >                                         ^
       > malloc.c:54:21: note: include the header <stdlib.h> or explicitly provide a declaration for 'realloc'
       > ./malloc.h:64:6: note: expanded from macro 'drealloc'
       >                                         mrealloc(md, (void*)(ptr), (size))
       >                                         ^
       > ./malloc.h:39:34: note: expanded from macro 'mrealloc'
       > # define mrealloc(md, ptr, size)        realloc(ptr, size)
       >                                         ^
       > 3 errors generated.
       > make[1]: *** [<builtin>: malloc.o] Error 1
       > make[1]: Leaving directory '/private/tmp/nix-build-tinyfugue-50b8.drv-0/tf-50b8/src'
       > make: *** [Makefile:18: files] Error 2
       For full logs, run 'nix log /nix/store/d2is2kbs43ykmzhw0b8pqr9nnhsrfp1q-tinyfugue-50b8.drv'.
error: 1 dependencies of derivation '/nix/store/dpb8xlv47g1hl98m7p5rg232w1rc7g9l-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wgr95pgkqa5pmy37ycbw75b5mfwld75v-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0dsxafh5xknl3rkjkhfjfbq0ya9lgm8i-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xdljff5cgrm7c4gm43z93pi7md1qmqcs-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yg7z0y8dyfgl4fvllc9wwmzhpzb62c20-activation-adam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1lx0l8m263k9mqhni3w450d9pp5f57l0-darwin-system-24.11.20240616.b60ebf5+darwin4.29b3096.drv' failed to build
```

**Comment by erratic-pattern** [comment]
Seems like the nix package only supports Linux as a target.

**Comment by erratic-pattern** [comment]
I submitted an issue to nixpkgs as well https://github.com/NixOS/nixpkgs/issues/321605

**Comment by erratic-pattern** [comment]
full output from running `export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1; nix-shell -p tinyfugue`

https://gist.github.com/erratic-pattern/33d57aea6e4a12058a9954e3a001af2e

**Comment by erratic-pattern** [comment]
full logs from running `export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1; nix-shell -p blightmud`

https://gist.github.com/erratic-pattern/90d8f97ab083f5caa575cb98d8002b5e

**Comment by cpu** [comment]
Hi @erratic-pattern,

Thanks for opening an issue.

> I encountered an error when trying to build blightmud on a Macbook Pro M3 using home-manager and nix-darwin.

I'd be happy to review patches to add support but I don't have the hardware/interest to drive the effort myself.

**Comment by erratic-pattern** [comment]
any clue what the error could be related to?

I can definitely try to get it working but I don't know what all is used by
Blightmud in terms of C libraries.

I assume at minimum it would need the Mac SDK packages to build any C
libraries. I can try dropping those into the build inputs to see if that's
all it needs

**Comment by cpu** [comment]
@erratic-pattern If you confirm the fixes in https://github.com/NixOS/nixpkgs/pull/321727 worked for you I can backport them to the flake in this repo.

**Comment by erratic-pattern** [comment]
I able to run the command mentioned [here](https://github.com/NixOS/nixpkgs/issues/321605#issuecomment-2183969843) successfully. I haven't tested the change with my flake config yet, since I either need to checkout nixpkgs or wait until it hits unstable channel, but I think it's fair to assume that it will work. If I have some time today I'll try with a local nixpkgs checkout.

**Comment by erratic-pattern** [comment]
This is now on unstable and working 👍

**Comment by LiquidityC** [comment]
This looks done so I'll close. Ping if I'm wrong.
