### ISSUE TITLE
Idenfitiers for timers, triggers, trigger groups, and aliases

### ISSUE THREAD

**Issue by justinpopa** [Blightmud/Blightmud#1098]
It would be nice if we could set IDs on these items at their creation time, preferably with strings rather than integers. I often have to enable/disable triggers in my scripts and referencing a changing integer(depending on the order in which things are added to blight) across multiple scripts means that I have to create and maintain a global that contains all the current trigger ID's, and make sure that any scripts adding items. It's a little cumbersome for me because I am using plugins written for MUSHClient, and so I'm in some cases having to go in and modify them to fit the blightmud paradigm.

**Comment by LiquidityC** [comment]
I get what you are saying here but I'd like some background on how you are utilizing the triggers and aliases. Am I understanding it correctly that you aren't using the trigger object or trigger group object?

eg.
```lua
local t1 = trigger.add("^.* enters from the \\w+\\.$", {}, function (m)
    -- Do something
end)

-- Other operations

t1:set_enabled(some_rule)
```

alternatively with groups:

```lua
local group = trigger.add_group()

local hilight = function (_, l)
    print(cformat("<red>%s<reset>", l:line()))
end

group:add("^Some trigger\\.$", {gag=true}, hilight)
group:add("^Some other trigger\\.$", {gag=true}, hilight)

-- And then
group:set_enabled(some_condition)
```
