### ISSUE TITLE
Retrieve output buffer through lua

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#131]
Add a blight function which can retrieve all the data currently present in the
output buffer.

Eg.
```lua
blight:get_buffer(function (lines)
    for i,l in pairs(lines) 
        -- Do something with the line
    end
end)
```

**Comment by xvxx** [comment]
Any thoughts on how you'd implement this? I thought it'd be a quick fix, but looking at the code the `blight` module doesn't know anything about `screen` and we can't send a `rlua::Function` over a channel for the main event loop to call with the history. So it might require moving some things around.

**Comment by LiquidityC** [comment]
It'll be many steps. Change screen and history to not work with simple String types but instead hold `Line` objects in memory. You can then leverage the history buffer to retrieve lines currently on screen.

That screen change has been on my mind for a while. I thought I'd fix it next time I need to change something bigger in `screen.rs`

**Comment by LiquidityC** [comment]
I think this issue might be obsolete. With the possibility of hooking into all the mud output through `mud.add_output_listener()` and `mud.add_input_listener()` it should be possible to create a buffer of all existing output from the mud as well as user commands. So with just a few lines of scripting you should be able to build this feature rather easily. Hence I will close this. If anyone wants to build a more general/available solution to it you can easily create a plugin.

Closing
