### ISSUE TITLE
Add audio support

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#158]
As an opt in compile time feature (like tts) we would like to be able to play audio through lua functions.

The crate `rodio` should provide the needed functionality. Initially it should be possible to play two kinds of sound. Music and Sound. Music is intended for background music and secondary calls to play music should stop whatever is playing at the moment. There should be flags for how many times the audio is played or infinite loops.

Sound should be used for SFX and there shouldn't be a limit to simultaneous sounds. The same loop functionality should be present.

Beyond that a function to stop all sound or stop just the music needs to be available.

Sound paths should be file paths or an url. If an url is provided the audio should be fetched using `curl` the first time it's called. Subsequent calls should play the file on disk. 

Help files etc need to exist. An alternative help file if you compile without sound is also needed.

**Comment by mikeggh** [comment]
What's the suggested way to compile without this, and/or tts?

**Comment by LiquidityC** [comment]
TTS support is controlled by a feature flag. There is no feature flag for audio support.
