### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#194]
# Version 3.0

This is the main task wrapping all the changes in store for the next major release. It won't add much new functionality but it will open up blightmud a lot more for future plugins and similar.
Issues should be created for every point on the list. If you want to work on something but can't find the issue then create it.

## Breaking changes

- [x] Introduce a Lua object `Line` that mimics the current `Line.rs` but in lua. `lua::Line::from(model::Line)` ***blocker, needs doing first***
- [x] Send all mud output lines to lua as `Line` objects. I'm thinking `mud:add_output_listener(callback)`
- [x] Send all user input to lua as `Line` objects. `mud:add_input_listener(callback)`
- [x] Break out the trigger functions from `blight.rs` and re-build it in pure lua using the new `Regex` module. (new `trigger` module)
- [x] Break out the alias functions from `blight.rs` and re-build it in pure lua using the new `Regex` module. (new `alias` module)
- [x] Move the timer related code out of `blight` and put it in it's own module `timers`. This will have to remain a lua/rust hybrid because of the timer thread.
- [x] Move the logging related stuff from `blight` into a new `logging` module.
- [x] Move all the mud related stuff **send, send_bytes, mud_output, disconnect, connect, on_(dis)connect** to the new `mud` module mentioned above.
- [x] Move script related functions (**load, reset**) from `blight` to a new `script` module.
- [x] Move store functions from blight to a new `store` module. Also move the session store from `core` to this new module and give the methods names based on storage type.
- [x] Move settings aliases out of rust into a `settings` module and setup the aliases in lua instead.

Note, the above should leave `blight` with only one function: **output**. I think that will still belong. Because it's about doing stuff with blightmuds screen and display. Unrelated to any other system. Also people will most likely only use print now.

## Think about
Here are some additional things that should be kept in mind if you're helping out with the next big version.

### Naming
Some functions in `blight` currently have names that pertain to their responsibility. When creating a more logical module system some of these names will be stupid. If you feel that way then change the name. Eg. `blight:start_logging()` **=>** `logging:start()`

### Lua code
Some of these changes will break existing scripts we have in place. `gmcp`, `msdp`, `macros` etc. Make sure you check these. Simple find/replace will most likely suffice.

### Testing
When writing the `regex.rs` module I introduced a new way of testing in that file. Before all tests for lua modules were done in the `lua_script.rs` which was ugly an not very *unit testy*. Since I/we will be making a lot of new modules. Writing as close to 100% testing as possible of those files is mandatory.

### Help files
Don't forget to update corresponding help files when you apply some of the issues above. If a help file doesn't exist or you want to split one up then do that. They are too long as it is.

**Comment by LiquidityC** [comment]
If anyone has experience with lua unit testing then please speak up. If we add it now it will save us time in the future.

**Comment by xvxx** [comment]
Personally I think it would be great if we could avoid external Lua dependencies. There are two approaches I usually take when working with embedded Lua: either just writing a few simple helpers and writing/running the tests in Lua itelf (like defining an `assert()` function), or creating a Rust test that knows how to load and test Lua code. 

In other words, it'd be great if `cargo test` ran and reported on the Lua tests as if they were Rust tests, while at the same time keeping the Lua tests in `*.lua` files so they render correctly in everyone's editor.

I usually do this by creating a `fn test_lua()` function that is set `#[test]` and does all the loading, `assert_eq!()`, etc in there.

Obviously this is a bit hand wavy, I just think it's key to have the least amount of friction possible so it's easy for contributors to run the tests and add their own without much trouble.

One thing I do think we'll need no matter what is to pull out some of the "pretty printing" logic from the `/lua` command and re-use that in tests, so we can print tables and other Lua data structures during failures to aid debugging.

Depending on how quickly you want to get moving I could take a stab at this to show what I mean.

**Comment by LiquidityC** [comment]
That sounds smart. We could but a test in lua_script.rs that just loads and runs our lua test files and fails if they fail using asserts. I'll take a look once we get to that point.

**Comment by Xandaros** [comment]
I had a look at luaunit yesterday. It ships as a single Lua file that you can just include with your project, so in those cases, extra dependencies are probably not a huge issue.

That said, I don't think luaunit is what we need. It handles everything itself, including the printing of test results, and it doesn't look like you can change that.

**Comment by xvxx** [comment]
I've also worked a lot with [Busted](https://olivinelabs.com/busted/), but similar to luaunit I think it relies on its own runner so it's more difficult to hook into `cargo test`. I do like its assertions a lot tho, `assert.is_nil()` and such read nicely to me. 

I don't have anything against including extra dependencies in the project, what I meant by "external" is that I don't think we should be requiring a developer to have their own version of Lua installed with LuaRocks, different packages, etc in order to run the project. It's nice when `cargo test` will fetch all your dependencies and run everything for you, and it makes it easier for new contributors to just dive right in. I've seen situations where everything in the project works, except loading the code through the test suite because it uses a third party system. So the tests won't run, and you've got to create an issue to make sure you're on the right version of Lua and your load paths are setup, etc etc etc. There are situations where you definitely need an external dependency and can't get around it of course, but for test helpers/assertions I just don't think it's worth putting the extra friction between a developer and a contribution. 

I don't know how robust our pretty printer is right now, it might be perfect for the job, but if we do want to use something standard this is what I use in every Lua project nowadays: https://github.com/kikito/inspect.lua

**Comment by LiquidityC** [comment]
My first attempt at this will be clean lua. I'll try and write something where one can script up the tests you want run and this file in turn should work to run on its own. We can then add some rust tests that simply `include_str!` that file and run it. An error code and a message should suffice. To investigate an error you can just run the lua file externally and see what's being printed.

**Comment by LiquidityC** [comment]
The function `blight:gag()` won't work as it used to now. My suggestion is this. In the future callbacks for trigger/alias matches will take two arguments. The matches and the line object. Eg.
```lua
trigger:add("^You recover some mana.$", {}, function (matches, line)
    line:gag(true)
end)
```

**Comment by LiquidityC** [comment]
Just a heads up! If you are using the `dev` branch for your mudding needs then all your triggers need updating now.

**Comment by LiquidityC** [comment]
Same thing goes for Aliases now

**Comment by LiquidityC** [comment]
#238 is the last issue in line for version 3. After it's merged and done I'm forking a release candidate for final testing before release.
