### ISSUE TITLE
Crash at start: `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by acacio** [Blightmud/Blightmud#235]
**Describe the bug**
Crash at game start.

**To Reproduce**
Build from source, just cargo build and cargo run. Crash at start.

**What terminal are you using?**
MacOS Big Sur Terminal
TERM=xterm-256color

Running on Ubuntu 18.04.5 LTS

Crash log:
----------
name = 'blightmud'
operating_system = 'unix:Ubuntu'
crate_version = '2.3.1'
explanation = '''
Panic occurred in file 'src/net/check_version.rs' at line 33
'''
cause = 'called `Option::unwrap()` on a `None` value'
method = 'Panic'
backtrace = '''

   0: 0x55deff095756 - blightmud::net::check_version::check_latest_version::{{cl
                at /home/acacio/src/Blightmud-2.3.1/src/net/check_version.rs:33
   1: 0x55defeed8703 - std::sys_common::backtrace::__rust_begin_short_backtrace:
                at /usr/src/rustc-1.43.0/src/libstd/sys_common/backtrace.rs:130
   2: 0x55defef02423 - std::thread::Builder::spawn_unchecked::{{closure}}::{{clo
                at /usr/src/rustc-1.43.0/src/libstd/thread/mod.rs:475
   3: 0x55defef0c723 - <std::panic::AssertUnwindSafe<F> as core::ops::function::
                at /usr/src/rustc-1.43.0/src/libstd/panic.rs:318
   4: 0x55defeee925b - std::panicking::try::do_call::h93754f82f0f2d234
                at /usr/src/rustc-1.43.0/src/libstd/panicking.rs:303
   5: 0x55deffb6b637 - __rust_maybe_catch_panic
                at /usr/src/rustc-1.43.0/src/libpanic_unwind/lib.rs:86
   6: 0x55defeee8b00 - std::panicking::try::hf4d23d5606eada60
                at /usr/src/rustc-1.43.0/src/libstd/panicking.rs:281
   7: 0x55defef0cb33 - std::panic::catch_unwind::h59e49b7a794a3f6c
                at /usr/src/rustc-1.43.0/src/libstd/panic.rs:394
   8: 0x55defef0135a - std::thread::Builder::spawn_unchecked::{{closure}}::h5ebd
                at /usr/src/rustc-1.43.0/src/libstd/thread/mod.rs:474
   9: 0x55defefd06ae - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2
                at /usr/src/rustc-1.43.0/src/libcore/ops/function.rs:232
  10: 0x55deffb5159f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>:
                at /usr/src/rustc-1.43.0/src/liballoc/boxed.rs:1017
  11: 0x55deffb6537d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>:
                at /usr/src/rustc-1.43.0/src/liballoc/boxed.rs:1017
                 - std::sys_common::thread::start_thread::h94e60cf98e4db105
                at /usr/src/rustc-1.43.0/src/libstd/sys_common/thread.rs:13
  12: 0x55deffb59136 - std::sys::unix::thread::Thread::new::thread_start::hfdb2b
                at /usr/src/rustc-1.43.0/src/libstd/sys/unix/thread.rs:80
  13: 0x7f73aa5086db - start_thread
  14: 0x7f73aa01971f - __clone
  15:        0x0 - <unresolved>'''

**Comment by LiquidityC** [comment]
I've stumbled upon this. When was your last pull from the dev branch? I think I patched it yesterday.

**Comment by LiquidityC** [comment]
Oh, sorry. Yes you are on the master branch. I'm patching this now. Should be fixed in 30 mins. Sorry.

**Comment by LiquidityC** [comment]
If you pulled from master branch then a fresh pull should work now. Homebrew will be another few minutes. Please close if your problem has been fixed.

**Comment by LiquidityC** [comment]
Closing as it's been fixed.
