### ISSUE TITLE
Remove most unwraps

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#236]
Problems like #235 keep popping up and while the new version does fix the reason those values become `None`, even if they did become `None` again in the future, that should not cause a panic.
A simple message to the user that the version check failed should be sufficient - the rest of Blightmud can continue without issue.

I suggest going over every `unwrap` and `expect` in the code and thinking about whether a panic is actually appropriate in those cases. I have a feeling that in many cases, it won't be.

`unwrap`s should probably be universally turned into `expect`s, as well. At least we can tell users what went wrong and don't leave them with just a source filename and line number.

**Comment by LiquidityC** [comment]
Yup. I've taken the time to clean out a few every once in a while. But we can leave this task open and available for anyone who's up for some chore work.

Commits of any size are fine.

**Comment by jacobmischka** [comment]
I've been browsing through rust hacktoberfest projects and came across this. Is this still valid? I just spent some time reviewing all of the `.unwrap()`s, and the vast majority of them are simply on channel `.send()` calls (often which are being used to actually log other errors, lol). Nearly all others are unwrapping thread spawning, which shouldn't be passed around in Results anyway (https://github.com/dtolnay/anyhow/issues/81#issuecomment-609171265). I didn't really come across many cases where it would be ergonomic to return Results instead.

I spent a little while replacing them all with something vague like `.expect("Failed sending event")`, but that's not particularly great either honestly. Other than that, I think the best option is probably to wrap the event channels in a custom struct that handles that automatically, but that also adds a little bit of complexity.

Which option sounds better? Or is either worth it? The only reason why sending to a channel should fail is if the channel has been dropped, which shouldn't really ever be the case.

Thanks!

**Comment by LiquidityC** [comment]
Hello. Thanks for taking the time to look into this. This issue has been a long standing one and at this point I think we've eliminated most of the "hanging" unwraps. It is as you say. We don't really care about the unwraps on send because it shouldn't happen and if it does the application needs to crash anyways.
