### ISSUE TITLE
Move settings aliases to lua

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#238]
As described in #194 

Currently there are a bunch of `/set` and `/settings` commands that could be moved to a lua module. The aliases could then be created in lua instead.

The module should allow scripts to get and set settings as well as retrieve all available settings.

**Comment by singularpoint** [comment]
I can take the issue.

**Comment by LiquidityC** [comment]
@singularpoint If you got the time you are welcome to start this one. I have limited time until next year. I'll assign you. Just comment if you'd rather not :wink:

**Comment by LiquidityC** [comment]
@xvxx You have any input on this issue? If I'm not mistaken you presented the idea that created it :smile: 
Or did I sum it up just about right in the details above?
