### ISSUE TITLE
Output view navigation.

### ISSUE THREAD

**Issue by lisdude** [Blightmud/Blightmud#25]
When scrolling through output view, a couple of things would be really nice:

- Search
    - / - Begin search
    - n - Next result (searching downward)
    - p - Previous result (searching upward)
    - N - Last result
    - P - First result
- Jump to previously echoed commands
    - Alt-Spacebar - Jump to the last command you typed in the output view. Press again will go back to the command before that, and so on.

**Comment by LiquidityC** [comment]
Seems reasonable

**Comment by LiquidityC** [comment]
I finally got to this one. Some stuff left on the PR like tests and doc. Other then that it works.
This is the solution:

- `ctrl + pgup/pgdn` is the default binding for navigating back and forth between "last input" positions.
- `/s <regex>` or `/search <regex>` will initiate a search "upwards" through output history.
- `ctrl + up/dn` will jump back and forth between matches.

The searching logic and bindings are built in Lua, the actual search and scroll is inside rust in the UI.
All bindings can be altered to your liking and aliases can be re-written.

Blightmud will do it's best to attempt to highlight matches. It does sometimes mess up other ascii colors in the history or vice versa. But I find this to be a minor issue.

Input searching is just a search for what we know the "blightmud sent input" lines look like. So if a mud sends very similar lines this might hit other output in the history. I don't see this as a major problem either.
