### ISSUE TITLE
Building with TTS

### ISSUE THREAD

**Issue by vincent-lg** [Blightmud/Blightmud#250]
Hello,
It might be great to have some basic documentation on how to build `blightmud` with TTS enabled.  The `README` file does advise for `all-features`, but when I run it I have errors without much explanation.  I'm obviously missing libraries I should install with `apt` in my case, before running `cargo build`..  I know that library names do not always match on Linux and it's tricky to get (especially since someone with a screen reader might have all of them already installed) but it would be worth it adding some documentation on that, even if short.  Those of us wanting to build with `rust`, after all, can do additional research with useful error messages.
Thanks for the great work on this client, I was getting desperate enough to code my very own, just for my purpose, glad someone else did it (and better than I could have too)!

**Comment by Xandaros** [comment]
Getting TTS to work is, frankly, quite a mess.
In short: You will need a functioning [`speech-dispatcher`](https://freebsoft.org/speechd) working.

I think explaining how exactly this is done is out of scope for our README, but maybe linking to some instructions would be good. I actually can't find anything currently. I remember struggling quite a bit with it, though.
One thing that tripped me up: Apart from speech-dispatcher, you actually need a TTS software. speech-dispatcher is, as the name might imply, just a dispatcher - it doesn't do any speech synthesis itself.

**Comment by LiquidityC** [comment]
Yes, this detailing is quite lackluster I realize. I will double-check my setup and update the documentation to match. For now without checking my "playing" computer where I user this myself it goes something like this:

You need to install **speech-dispatcher** and a voice synthesizer to go with it in my case I'm using **espeak**. If you are on a debain based system you will need some **dev** packages to go with the binary packages.

Assuming we are talking deb based linux this should be: **apt-get install speech-dispatcher speech-dispatcher-espeak libspeechd-dev espeak**

For a *pacman* dist (Arch, Manjaro) it should suffice with: **pacman -S speech-dispatcher espeak** (If i recall correctly)

I'll drop another comment notifying when the README has been updated.

**Comment by LiquidityC** [comment]
Documentation for TTS build has been updated with deps for Ubuntu and Arch
