### ISSUE TITLE
help config_scripts example fails on core:store

### ISSUE THREAD

**Issue by tlashua** [Blightmud/Blightmud#268]
When trying to use the example from /help config_scripts, it complains: 
[!!] [Lua] Script error:
[!!]     runtime error: [string "/Users/tim/.config/blightmud"]:3: attempt to call a nil value (meth[!!]     stack traceback:
[!!]         [C]: in method 'read'
[!!]         [string "/Users/tim/.config/blightmud"]:3: in main chunk

maybe caused by: host = core:read("cur_host"),

**Comment by LiquidityC** [comment]
Thanks for the issue. 

It's a miss by me that there was "old" code in that example.

`core:read` should be `store.session_read`
`core:write` should be `store.session_write`

If you encounter any similar issues `/help changes` might hold the answer to my sloppy errors.

However the `/help config_scripts` has already been patched and released in version 3.0.3 so I will close this issue.

Thanks again for reporting it to me/us.
