### ISSUE TITLE
AUR package with TTS support?

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#274]
Currently it is not possible to install Blightmud from the AUR with TTS support.

It might be a good idea to add a `blightmud-tts` package that includes TTS support. If we add more such feature gates in the future, this will very quickly become unmaintainable, but I don't really see that happening.
Alternatively, since an AUR package will pull in its dependencies, simply enabling TTS for the default build might not be terrible.

It's an extra 20 MB and clutter in the package database, but that doesn't seem very much. Not having an easy-to-install TTS version seems worse in my opinion.

**Comment by LiquidityC** [comment]
Makes sense. I've made a decision already that unless there is very good reason, TTS will be the first and last feature flag I add. The plugin system should suffice as a "feature picker" in the future.
