### ISSUE TITLE
Partial line repeated above where it should be.

### ISSUE THREAD

**Issue by lisdude** [Blightmud/Blightmud#284]
What seems to happen is that a bit of text from the middle of a long stream of text will get duplicated, in part, in random lines above it. I'll try to illustrate with a screenshot showing a diff between my regular client (on the left) and the Blightmud output (on the right).

You can see the line beginning with '1607011755' is displayed correctly on line 43 in Blightmud. But then you look above line 43 and you can see that it's been partially duplicated three times.

<img width="1271" alt="Screen Shot 2021-03-28 at 5 19 33 PM" src="https://user-images.githubusercontent.com/4994688/112770011-14dbcb00-8fea-11eb-9663-38caa66604b4.png">

**Steps to Reproduce**
1. Connect to lisdude.com:1180
2. Type: longline2

It may take a few tries to get it to happen. Or you could try a combination of 'longline' and 'longline2'.

**Comment by LiquidityC** [comment]
This one is being very difficult to reproduce...
What terminal are you using?

**Comment by lisdude** [comment]
I've reproduced it with Kitty 0.19.3, iTerm2 3.4.4, Apple's Terminal, and Blink Shell on iOS.

Unfortunately I haven't pinned down a reliable way to make it happen every time on demand. Sometimes it takes several longline2's before scrolling up before you see the effect. I'll keep trying various ways to make it happen and see if I can find a reliable way to reproduce it.

**Comment by LiquidityC** [comment]
Ok, managed to recreate it. It was due to concurrency where we would receive the next prompt before printing the current one. Not an easy debug. But I've submitted a PR. I'll merge into master, merge that into dev and do a patch release when I get a few spare minutes.

Thanks for the spot @lisdude :smile:
