### ISSUE TITLE
Unable to connect to saved TLS servers.

### ISSUE THREAD

**Issue by lisdude** [Blightmud/Blightmud#317]
**Describe the bug**
When using `/connect` to connect to a saved TLS world, connect scripts load but no connection is actually made to the server. 

**To Reproduce**
1. `/add_server miriani toastsoft.net 1443 true`
2. `/connect miriani`

Whereas connecting manually works just fine:
1. `/connect toastsoft.net 1443 tls`

**What terminal are you using?**
iTerm2 3.4.8

**Comment by LiquidityC** [comment]
This handling moved to a lua implementation. Most likely I messed it up. I'll check.

`macros.lua` if you want to take a look.

**Comment by LiquidityC** [comment]
Found it: https://github.com/Blightmud/Blightmud/blob/4bc91ffd0dd7fc79865a7745b280da5e7bfed31f/resources/lua/macros.lua#L135

I can fix it in the morning.

Just one arg missing on that line: `mud.connect(server.host, server.port, server.tls)`
