### ISSUE TITLE
Basic character management

### ISSUE THREAD

**Issue by icopp** [Blightmud/Blightmud#330]
A hopefully not-too-complicated feature enhancement could be basic character management, where Blightmud could save a name and optionally password for each character for a given world, provide a very basic auto-login process, and group logs based on character names.

Appropriate commands could look something like this:

```
/set <setting> <server name> <server-specific setting>
/set login_type <server name> <'mush', 'mud', or 'iron_realms'>

/add_character <server> <login name> [login password] [alias to use for /connect]

/add_server discworld discworld.starturtle.net 4242
/set login_type discworld mud
/add_character discworld Twoflower hunter42
/add_character discworld Rincewind

/add_server lambda lambda.moo.mud.org 8888
/set login_type lambda mush
/add_character lambda Wizzlestick hunter42

/add_server m-u-s-h mush.pennmush.org 4201
/set login_type m-u-s-h mush
/add_character m-u-s-h "Johann the Great" hunter42 Johann

/connect discworld
/connect discworld Twoflower
/connect m-u-s-h Johann
```

For connections associated with a character (whether or not a password is saved), logs would get saved to `<hostname>/<character name>/<date-time>.log` rather than just `<hostname>/<date-time>.log`.

My mental model here is based off Atlantis for macOS, which implements basically this general structure, but also with a larger framework for also having settings per-character (aliases, UI settings like fonts, etc) that override the defaults set for each server, which override the defaults set app-wide.

**Comment by LiquidityC** [comment]
This sounds like useful functionality. However I would say that this is a definite plugin. 

Everything needed for adding this functionality is available through lua.

**Comment by Xandaros** [comment]
Some ideas:
We have a new `settings` plugin, with roughly this API:

- `setting.add(name: str, type: str, default: Option<any>)`
- `setting.get(name: str) -> any`
- `setting.set(name: str, value: any)`
- `setting.on_change(name: str, callback: fn(name: str, value: str))`
- `setting.list(name: Option<str>) -> List<(str, any)>`

names are a `.` separated path. For example `blightmud.do_the_thing`
You change settings with the `/set` command.

Then we also have a new `character` plugin, with roughly this API:

- `character.add(server: str, name: str, login_type: LoginType, password: Option<str>)` (`LoginType` being an enum)
- `character.remove(server: str, name: str)`
- `character.on_login(server: Option<str>, name: Option<str>, callback: fn(server: str, name: str))`
- `character.list(server: str) -> List<str>`

We might also want to make use of a `Character` object, in which case, we also have:

- `character.get(server: str, name: str) -> Character`
- `character.register(character: Character)`
- `character.list(server: str) -> List<Character>` (replacing the one above)
- `Character.new(server: str, name: str, login_type: LoginType, password: Option<str>)`
- `Character:setters_and_getters...`

You can change individual characters with the `/set` command. For example, to change the password:
`/set servers.<server>.characters.<name>.password <new_password>`
There should absolutely be a custom tab-completion handler for this. Double-tab should show possible remaining options

The reason I am proposing this settings system is that it easily covers more than just characters and allows plugins to add their own persistent settings.

With the `on_login` callback, character-specific aliases and such should be fairly simple to implement. You just enable/disable alias groups depending on the character.

Open questions:

- Should changes to characters via Lua be persisted? Do we maybe want a function that you need to call to persist changes?
- Do we change existing `/set` commands? Not technically necessary, but we might want to group them in a `blightmud` thing. Like `blightmud.logging_enabled`
- Maybe we don't need commands for characters at all. Defining them in a Lua file would work and we wouldn't have to worry about persistence
- Should there be a function for deleting settings (I suppose setting to `nil` should work)

**Comment by LiquidityC** [comment]
Sounds like a sound approach. If someone does get started on this I'd be happy to take on changes that would improve plugin development since it's rather "best guess" at the moment. 

However these kinds of extensions won't make it into the BM source code. They are better off as third party plugins. That would probably allow a more active development of the functionality too. Plugins can easily have a rolling release approach.
