### ISSUE TITLE
Confirm quit even with /quit

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#332]
It is impossible to quit Blightmud with `/quit` if confirmations are enabled.

I don't think `confirm_quit` should apply to the `/quit` or `/q` commands and should instead quit immediately, regardless of the `confirm_quit` setting

**Comment by LiquidityC** [comment]
You think confirm_quit should only apply to `ctrl+c` and not require an additional `ctrl+c` after entering `/quit`?

**Comment by Xandaros** [comment]
Exactly. It's not like you accidentally type in `/quit`

**Comment by LiquidityC** [comment]
I have 🙂

But yes I'm prepared to agree with you. I generally use `ctrl+c` to quit and then the double tap feels natural. It does not feel natural after typing `/q` or `/quit`. 

Changing a setting behavior is not a breaking change. Right?
