### ISSUE TITLE
scroll_split setting does not take effect immediately

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#336]
Changing `scroll_split` does not take effect until the second time you scroll.

To reproduce:
Change the setting.
Scroll up. If it still using the old setting.
Scroll back down.
Scroll up. It is now using the new setting.

**Comment by LiquidityC** [comment]
This is a known "feature". You can also force the change by pressing `ctrl+l` after changing the setting. It can be fixed by forcing a screen reset after setting changes if someone wants to take a look at this. However lua currently can't force those so that's where one would have to start.

**Comment by LiquidityC** [comment]
This one was sneakily patched last night 😊
