### ISSUE TITLE
Scrolling In Reader Mode Not Returning To Bottom After Command

### ISSUE THREAD

**Issue by ironcross32** [Blightmud/Blightmud#367]
**Describe the bug**
when Reader mode is enabled, and the page up and page down keys are used to scroll up such that the bottom of the screen is no longer visible, any new commands entered or anything sent to the MUD is essentially ignored by the screen reader. This is good in the sense that output from the MUD won't cause someone to lose their place with the screen reader, however, this is problematic in the extreme when input does not trigger the screen position to the bottom.

What should happen is the following. When a command is entered and the screen is scrolled so that it will not be visible, the position should be returned back to the bottom and this information should be presented as new.
**To Reproduce**
How can we recreate this bug?
With reader mode enabled, and a sufficient length of text in the terminal, scroll up so the bottom of the screen is no longer visible. Then enter commands. These can either be BlightMUD commands, or anything you'd normally send to the MUD. Notice that this information is never given to the screen reader at all, and that for all intents and purposes, the client seems almost unresponsive.
**What terminal are you using?**
Just the name of the terminal client you are currently running.
openssh
**What mud were you playing?**
Host? Port? Website?
FluxWorld centauri.servegame.com 7777
**Screenshots**

**Comment by Xandaros** [comment]
Honestly, I'd prefer this in non-reader mode, as well. Maybe as a setting?

**Comment by ironcross32** [comment]
> Honestly, I'd prefer this in non-reader mode, as well. Maybe as a setting?

If it's a setting, it should be turned on when Reader mode is. Without this, it can appear as if the client has hung, as the screen reader user will not get anything back from the client, even though it's functioning, just not automatically scrolling to the bottom.

**Comment by LiquidityC** [comment]
We'll make it default behavior for both views without a setting. I can't see any valid use case where you are sending commands whilst reading the scroll history. Feels like having a setting would be overengineering.

**Comment by LiquidityC** [comment]
If anyone wants to attempt solving this it should be pretty simple. We have a special function `print_send()` that prints user input. If we are scrolled when that function triggers the scroll should be reset. Resetting scroll is also an available trait function.
