### ISSUE TITLE
Blightmud -c anywhere.org:6715 Panic: No option 'no-verify' defined

### ISSUE THREAD

**Issue by tlashua** [Blightmud/Blightmud#382]
branch: dev

when -c is given on the command line, it checks for --no-verify and fails.

Panic occurred in file '/Users/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.21/src/lib.rs' at line 799
cause = '''No option 'no-verify' defined'''

https://github.com/Blightmud/Blightmud/blob/54781cf4a851a7f71d0bf047660accba6b7c64b0/src/main.rs#L159

This fixes it.
```
opts.optflag(
       "n",
        //  "--no-verify",
       "no-verify",
        "Don't verify the cert for the TLS connection",
    );
```

**Comment by LiquidityC** [comment]
Oops. Stupid mistake by me. Should be an easy fix. Thanks for reporting it.

**Comment by tlashua** [comment]
> Oops. Stupid mistake by me. Should be an easy fix. Thanks for reporting it.

The fix I posted works, at least locally for me, just delete the '--'.  I tried to write a test for it, but couldn't quite figure that out otherwise would have opened a PR.

**Comment by LiquidityC** [comment]
I hav eno good framework for full integration tests for blightmud so yes. These things are hard to test. Probably why I missed it in the first place. Should be good now though :wink:
