### ISSUE TITLE
Option for same-line command display.

### ISSUE THREAD

**Issue by lhandf** [Blightmud/Blightmud#387]
Currently, when a prompt is displayed, there is a blank line underneath if no command was entered during said prompt:

```
100hp 100m -
>
```
This is also the case when a command is entered.

It would be nice to have the option to display the command (or lack thereof) on the same line as the prompt, thus avoiding blank lines:

```
100hp 100m - command
```

**Comment by LiquidityC** [comment]
Ok, so for the first request you can achieve this easily using an alias:
```lua
alias.add("^$", function (_, line)
    line:gag(true)                
end)                              
```

The second one will be a bit more tricky based on how Blightmud handles lines and drawing. I can give it a try but no promises.
