### ISSUE TITLE
Color is sometimes lost in the scrollback buffer.

### ISSUE THREAD

**Issue by lhandf** [Blightmud/Blightmud#388]
**Describe the bug**
Paragraphs of colored text appear to lose color information after the first line wrap.

**To Reproduce**
- Have the MUD display a colored paragraph.
- Initiate the scrollback buffer.

**What terminal are you using?**
urxvt

**What mud were you playing?**
Lusternia

**Screenshots**
This first screenshot shows how it looks in the normal buffer:
![multiline2](https://user-images.githubusercontent.com/1622326/131885124-91fc913b-1b83-4e5d-82b1-71f4cfb9d7a9.png)

This second screenshot shows how it looks when in the scrollback buffer:
![multiline1](https://user-images.githubusercontent.com/1622326/131885125-07e56d68-6f50-4c60-9c68-b1d8e6349c1b.png)

**Comment by LiquidityC** [comment]
I've been aware of this one for quite some time. It's annoyed me but I never got around to looking into it because I thought it would be a tricky fix. Turns out it was 2 lines.
