### ISSUE TITLE
If try to connect to the wrong port, I can't interrupt the process with ctrl-C (and am thereby stuck!)

### ISSUE THREAD

**Issue by atroche** [Blightmud/Blightmud#389]
**Describe the bug**

Hi :)

I've been stuck on this screen for about a minute now:
![image](https://user-images.githubusercontent.com/29839/132162372-2c9d4e27-84db-430b-a51b-6195ffdbe43d.png)

The port is actually 4001.

**To Reproduce**

By doing cargo run on 4da0777309b66933cdd060803f83f98848482b02 and doing:

`/connect cogg.contrarium.net 4100`

**What terminal are you using?**
gnome-terminal

**What mud were you playing?**

cogg.contrarium.net

**Screenshots**

**Comment by LiquidityC** [comment]
Probably hung up on the connection timeout. I'll check it out
