### ISSUE TITLE
Client blocks when using socket.connect() and it has to wait for timeout

### ISSUE THREAD

**Issue by lhandf** [Blightmud/Blightmud#394]
**Describe the bug**
Client blocks when sending a newline character via `Socket:send()`.

**To Reproduce**
This works as expected:
```
local fd = nil

local function init()
    fd = socket.connect("localhost", 8000)
    fd:send("Chat capture initiated.")
end

init()
```
However, this blocks the client:
```
local fd = nil

local function init()
    fd = socket.connect("localhost", 8000)
    fd:send("Chat capture initiated.\n")
end

init()
```

**What terminal are you using?**
urxvt, using openbsd-netcat (`nc -lkp 8000`) which works fine if I use `nc localhost 8000` but not telnet, for some reason.

**What mud were you playing?**
Lusternia, but this happens before login.

**Comment by LiquidityC** [comment]
Hmm, odd. I use this a lot and I've never had the issue.

From what I can see it's not the newline causing it. I think your code is trying to connect twice to the same nc instance. The secondary connection is blocked by the first and this is what's causing the lock.

As a remedy for now, try this:
```lua
-- ...
if fd == nil
    fd = socket.connect("localhost", 8000)
end
fd:send("Chat capture initiated.\n")
-- ...
```

I'll see if we can add some better handling for this in the meantime.

**Comment by lhandf** [comment]
That does fix it. Most likely was some reload issue.

**Comment by LiquidityC** [comment]
I'll keep this open. Want a shorter timeout and a better error message so you understand what's going on.

Already have a half ready solution.
