### ISSUE TITLE
Add an option to mud.input to not modify command history.

### ISSUE THREAD

**Issue by lhandf** [Blightmud/Blightmud#414]
I have an alias in the form: `inf <word>`, which sends a command to the MUD. Additionally, I have a trigger to automatically resend this command when I receive balance back in the game. However, I had been sending `inf <word> <word2>` instead of `inf <word>`, using `mud.input`.

The issue is that when I move back up through the command history, it shows `inf <word> <word2>` rather than the previously manually entered command (`inf <word>`).

Not sure if this would be considered a bug, but I believe this option would be beneficial.

**Comment by LiquidityC** [comment]
This is a bug. Commands sent from scripts shouldn't end up in the command history. A result of the move to Lua command history.
