### ISSUE TITLE
Solus Linux/Unix crashing when TTS enabled

### ISSUE THREAD

**Issue by celtichawk** [Blightmud/Blightmud#431]
I've been running into this just now on several games I play.

My system is an AMD_64 Solus Linux distribution and I've built and installed Blightmud with TTS and use it with the --tts or /tts on setting, however am running into issues when playing. I'm using the latest packages as of writing but can't pull the current versions right now.

Crash log is below:

name = 'blightmud'
operating_system = 'unix:Unknown'
crate_version = '3.4.0 (v3.3.1-34-gb0d4bbd)'
explanation = '''
Panic occurred in file 'src/tts/speech_queue.rs' at line 93
'''
cause = 'Out of bounds access'
method = 'Panic'
backtrace = '''

   0: 0x56543cc210a3 - core::option::expect_failed::h7db74b1e3f5289b2
                at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1578
   1: 0x56543cd18921 - blightmud::tts::text_to_speech::run_tts::h9c535754782b258f
   2: 0x56543cc82ce0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfcae7eb42a16043f
   3: 0x56543cd653ca - core::ops::function::FnOnce::call_once{{vtable.shim}}::h88fcc7b994919366
   4: 0x56543d208c97 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572
                 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74
   5: 0x7f4f056c044d - <unresolved>
   6: 0x7f4f0549aa33 - clone
   7:        0x0 - <unresolved>'''

I've put it in the post since my browser is having issues with atttaching files.

**Comment by LiquidityC** [comment]
Thanks for reporting. This is a rather clear cut crash so shouldn't take long to fix.
