### ISSUE TITLE
encoding support other then utf8

### ISSUE THREAD

**Issue by d-murashkin** [Blightmud/Blightmud#498]
Describe the feature you would like added. Please be as detailed as possible.
Hi,
Is it hard to implement support of encodings other then utf8 (cp1251 for instance)?
I would be nice as some MUDs do not provide utf8 support

**Comment by LiquidityC** [comment]
It should be solvable but I can't say off the top of my head how much work it would be.

Could you provide an example mud or perhaps some screenshot examples? Both utf-8 and cp1252 are ascii compatible so it shouldn't look terrible in Blightmud as is. But perhaps this isn't English muds?

**Comment by d-murashkin** [comment]
Right,
the problem arises with Cyrillic letters.
As far as I understand, utf8 is hardcoded in Blightmud. Seems like there is a check on the encoding of a string, which gives en error message when an enconding other then utf8 is used. However I'm not familiar with Rust, so I might be wrong here.

**Comment by d-murashkin** [comment]
![screenshot](https://ibb.co/SsL6dmj)
Here is an example.
With "test" MUD returns strings with various encodings, but non of them work out (because none of them is utf8).
Also, when I type in cyrillic Blightmud writes "Unknown command: [...]" with four digits (seems like every digit correspond to one entered letter).

**Comment by LiquidityC** [comment]
It's more that Rust as a language is more or less hard coded to utf-8. Eg. The string type in rust is utf-8 bytes.

I'll take a look and see if we have any options here. It might boil down to massive changes though.

**Comment by troydm** [comment]
@LiquidityC the workaround would be to receive data in other encodings and convert it to utf-8 and when sending data convert it back to appropriate encoding, so for example server is working in Win1251, blightmud receives Win1251 data from server, converts it to UTF-8 and displays it, and when sending data to server you just convert UTF-8 to Win1251

You can use https://lib.rs/crates/encoding library for that

**Comment by LiquidityC** [comment]
Not a bad idea. I'll take a look when I get some time over. Currently a lot of deadlines at work.
