### ISSUE TITLE
Reconsider "mouse_enabled" defaulting to on?

### ISSUE THREAD

**Issue by cpu** [Blightmud/Blightmud#504]
This is somewhere between a feature request and a bug report, so let's call it a feature for now :-)

### Description

Presently Blightmud defaults the `mouse_enabled` setting to true when writing an initial v2 settings file:
https://github.com/Blightmud/Blightmud/blob/54781cf4a851a7f71d0bf047660accba6b7c64b0/src/tools/patch.rs#L182

In practice for myself, running Blightmud under `tmux` in a `alacritty` terminal emulator having this setting enabled is a confusing user experience. I'm unable to select any text with my mouse and so can't copy/paste. It took a little bit of sleuthing to discover the `mouse_enabled` setting and understand that turning it off restored what I expect is the common expectation of a terminal program: allowing mouse select/copy interactions.

This also seems to have been the experience of at least one other new user who came to the Discord #support channel with the same problem.

### Proposed Change

I propose that the `mouse_enabled` setting default to off.

The [documentation for settings](https://github.com/Blightmud/Blightmud/blob/dev/resources/help/settings.md) says:
> Experimental mouse scrolling support. Requires restart.

A few thoughts:

* If it's an experimental feature, maybe it shouldn't be enabled by default until it is battle tested and ready for use.
* Requiring a restart to change the value (seemingly even to disable it) means it's an extra hit to new user onboarding compared to other settings.
* I think most users have a default expectation of being able to select text in a terminal with their mouse. If the setting changes that behaviour it might make more sense opt-in.

Thanks!

**Comment by LiquidityC** [comment]
Defaulting this to off should be no problem. We should probably rename it to "mouse_scrolling" too. However when it is enabled it's default in all terminals we've come across to allow selecting when holding shift. So if you want mousewheel scrolling then you need to hold shift when selecting/pasting. 

The note about holding shift should probably make the helpfiles too.

**Comment by cpu** [comment]
> We should probably rename it to "mouse_scrolling" too

Great idea :+1: 

> The note about holding shift should probably make the helpfiles too.

Good point, if it were called out in the settings page it sounds like a pretty reasonable workaround. I haven't come across that trick before.

**Comment by cpu** [comment]
Thanks!
