### ISSUE TITLE
Blightmud is crashing when wraping a input line containing UTF-8/16 chars like emojis

### ISSUE THREAD

**Issue by cmetz** [Blightmud/Blightmud#528]
**Describe the bug**
Bligtmud is crashing when it tries to split a input line containing emojis or other utf-8 chars like 😀 or 󰖩. It also renders the input cursor offsets wrong for emojis.

**To Reproduce**
just type in only emojis until blightmud crashes, or one normal ascii cahracter and then only emojis, as it depends on your terminal width (even/odd) to actually split in an emoji

**What terminal are you using?**
wezterm / st

**What mud were you playing?**
home-mud for testing

**Screenshots**
Input cursor offset:
![image](https://user-images.githubusercontent.com/4041412/151072248-530d9494-7c3c-4b17-979d-7aca4886b435.png)

**Crash-Report**

[report-26bd67d3-1049-4f33-9c19-db4bd609edb2.toml.txt](https://github.com/Blightmud/Blightmud/files/7937716/report-26bd67d3-1049-4f33-9c19-db4bd609edb2.toml.txt)

The UTF-8/16 stuff is really no fun. Maybe other places in the code (output wraping) have a problem rendering such characters as well.

Thanks for your effort, it's really great how hard you are working on your project. 👍

**Comment by LiquidityC** [comment]
Thanks for the report. I'll have a fix for you in the morning. As for additional wrapping issues I don't think so. All the output should be safe. It's an oversight that the prompt had poor "fancy char" handling, typing emojis is rare.
That's probably why it's flow under the radar for so long. I guess the Russian player base has just been getting lucky i guess :worried:

**Comment by cmetz** [comment]
Thanks you!

 If testet it also in the reader_mode. There it is still crashing, i think the print_prompt_input needs the same treatment there as well. 

Also the rendering is somehow broken there completely when i type a emojy + something else the emoji gets non visible, i think this is because some of the glyphs like emojis are double-width characters and that's always a pain in terminal rending, but single-width glyphs like 󰣐 crash as well, but you realy need to fill up the input line  :)

[report-2c5dbbc3-d3e2-4ef7-8d30-07e8940ce3d4.toml,txt](https://github.com/Blightmud/Blightmud/files/7941175/report-2c5dbbc3-d3e2-4ef7-8d30-07e8940ce3d4.toml.txt)

**Comment by LiquidityC** [comment]
I'm aware of the reader_screen issue already. It's on its way.
