### ISSUE TITLE
Would be nice to be able to check the status of the connection

### ISSUE THREAD

**Issue by robg204** [Blightmud/Blightmud#553]
mud.on_connect and on_disconnect are nice, but being able to determine the current connection state at time of script load (or at any time, for that matter) would be great.

something like mud.isconnected returning true/false?

**Comment by LiquidityC** [comment]
Definitely doable. Will add this to the queue. On a side-note. When you're loading a script "mud.on_connect" will always get called if you're already connected to a mud when the script is loaded. Just an FYI until I get this in place.
