### ISSUE TITLE
/dc, /disconnect sometimes stop working.

### ISSUE THREAD

**Issue by robg204** [Blightmud/Blightmud#555]
**Describe the bug**
/dc and /disconnect often stop working for me.  Happens on both a wsl2/ubuntu x86 build, and an arm64 build on macosx. Same scripts on each host, no conflicting aliases or triggers, however seems to reproduce after longer connection times.  8-12 hours, tends to not happen under 4 hours connected.

output of /aliases just to show there are no conflicts:
  > /aliases
  [**]   42 : ^/cask$              +enabled
  [**]   40 : ^/goto \d+$          +enabled
  [**]   41 : ^/reset$             +enabled

**What terminal are you using?**
Windows Terminal, Alacritty

**What mud were you playing?**
3scapes.org 3200

**Screenshots**
Didn't screenshot, but /dc and /disconnect just do nothing.  I have not tried calling mud.disconnect() directly but will try that next time I experience this issue.

**Comment by robg204** [comment]
![image](https://user-images.githubusercontent.com/49252009/157597948-11b1072d-c32c-4fa3-9b61-61a209c7fd2c.png)

**Comment by LiquidityC** [comment]
Super odd. I'll see if I can figure it out based on this information.

**Comment by robg204** [comment]
Connection time, it turns out, is a bit of a red herring -- but extensive use of script.reset() does seem relevant.   I validated that mud.disconnect() remains intact as a function pointer when it stops working and dug deeper.  looking at mud.rs, I noticed disconnect was passing a connection_id into event.rs, and event.rs has this:

    if self.session.connection_id() == id && self.session.connected() {

I noticed that sef.session.disconnect() is called without such intensive checking elsewhere (ie: connect), and updated my local copy to

    if self.session.connected() {

and dropped all references to passing the connection ID into the disconnect event, and everything appears fixed.  I can submit a PR with all the required changes, but I'm not sure if the passing of this connection id was in preparation for something else.

The alternative would be to figure out and understand why the connection_id is getting mangled, as I clearly when the nuclear approach of not caring about the value at all.

**Comment by LiquidityC** [comment]
If I'm not completely mis-remembering. I think the connection ID is vital in the case of a reconnect `/rc`. So with the changes you made it shouldn't work to `/rc` a mud. It will just disconnect and be done with it.

**Comment by robg204** [comment]
`/rc` still works without an issue.  `/rc` doesn't care about the existing ID whatsoever.  The only thing that references it is `/dc`, as when I removed the reference to it rust started kicking warnings about it being unused, so I actually removed it entirely in my current working branch.  No issues with `/connect, /rc, /dc` since.

**Comment by LiquidityC** [comment]
Hmm. Must have been made obsolete and forgotten about then. I don't have access to the code right now and I've been sort of swamped at my new assignment. But send a me a PR and I'll check it out.
