### ISSUE TITLE
The last line in buffer is not printed

### ISSUE THREAD

**Issue by x1a0** [Blightmud/Blightmud#571]
Hi,

I am writing a proxy for the mud I am play.

I noticed that after sending some lines to Blightmud, the last line is always kept by Blightmud. It does not print it until more data are received. After reading the codes it seems it treats the last line as prompt or something? I didn't quite follow the logic.

Thanks.

**Comment by LiquidityC** [comment]
Even if it was treated as a prompt it would be printed. If the line isn't a prompt you should probably end it with a new line.
Is the proxy/mud using telnet GA or EOR or something similar? (the top bar of blightmud will tell you this).

What mud are you playing? If you connect directly to the mud without the proxy. Do you still get this behavior?

**Comment by x1a0** [comment]
It's the BatMud: `bat.org:2022` and it uses `GA`.

After some further trying:
If I send `line1\nline2\nline3\n` to Blightmud, it prints:
```
line 1
line 2

# then after some more data are received, it prints
line 3
<more data>
```

If I send `line1\nline2\nline3<GA>` to Blightmud, it prints all lines:
```
line 1
line 2
line 3
```

### Some context about the proxy

The proxy I am writing is to transform some special control codes that is supposed to be parsed by its office client - a Java application. These control codes are "wrapped" in special sequence such as:
```
\x1b<00some data\x1b>00
```
Tricky thing is such piece of data do not always come as its own line - some normal text could come right after the data in the same line, so the raw line is like:
```
\x1b<00some data\x1b>00 some normal text\r\n
```
A newline could also happen inside the special data:
```
\x1b<00some data\r\nsome data line 2\x1b>00 some normal text\r\n
```

The proxy will try to decode such special control codes and transform them into "lines" for generic Mud clients.

If connecting to Bat directly with Blightmud, it's hard to tell the behavior as such special control codes do not [always] end with newline or GA, so it's kinda expected that Blightmud does not print them immediately (If I understand it correctly...).

Thanks for quick response and sorry for wall of text.

**Comment by x1a0** [comment]
Oh and I also tried to connect to the proxy with `telnet` and everything printed in `telnet` as expected at least.

**Comment by LiquidityC** [comment]
Oh. Well Batmud uses a lot of the telnet bells and whistles. Since it's a GA enabled mud then Blightmud is behaving as it should according to the telnet proto. Just send a GA when you are done sending data and it should all draw nicely.

**Comment by x1a0** [comment]
Hmm with GA the print is fine but how should I match the line in triggers?
The same regex could match when it's ended with newline but now with GA it does not work :thinking:

**Comment by LiquidityC** [comment]
When you end a line with nothing but GA it is treated as a prompt so you have to set a prompt trigger. If you don't want it to be treated as a prompt just suffix it with a newline.

**Comment by x1a0** [comment]
Thanks for the help :pray:
