### ISSUE TITLE
some question about the regex feature

### ISSUE THREAD

**Issue by x1a0** [Blightmud/Blightmud#577]
Hi,

The text I want to match is:
```
Obvious exits are: n, e, se and s.
```

My trigger is defined as:
```lua
Exits.triggers:add("^Obvious exits are: (\\w+, )*(\\w+) and (\\w+)\\.$", {}, function (m)
    print("1:" .. tostring(m[1]))
    print("2:" .. tostring(m[2]))
    print("3:" .. tostring(m[3]))
    print("4:" .. tostring(m[4]))
    print("5:" .. tostring(m[5]))
    print("6:" .. tostring(m[6]))
    print("7:" .. tostring(m[7]))
    print("8:" .. tostring(m[8]))
    print("9:" .. tostring(m[9]))
    print("10:" .. tostring(m[10]))
end)
```

Result:
```sh
1:Obvious exits are: n, e, se and s.
2:e,
3:se
4:s
5:nil
6:nil
7:nil
8:nil
9:nil
10:nil
```

Question:
How can I get the `n, `? It seems all matches of `(\\w+, )*` are stacked in one slot and only the last one is returned?

**Comment by LiquidityC** [comment]
There are lots of regex resources and testers available for this sort of thing online. For this particular case I would capture everything after ':' and split on comma and ' and '.

**Comment by x1a0** [comment]
Ah okay... I thought it was a problem of Blightmud but apparently not. I will try other solutions. Thanks :+1:

**Comment by Xandaros** [comment]
Repeated capture groups only give you the last match. This is pretty common in many regex engines, so this isn't really all that surprising.

Personally, I'd keep it simple. Just capture everything after the `:`, replace the `and` with a `,`, remove spaces, and then split on `,`
