### ISSUE TITLE
Incorrect version set for 3.6.1 release

### ISSUE THREAD

**Issue by dolandemort** [Blightmud/Blightmud#588]
Unless I am doing something silly, I think you have set the version number for the latest release incorrectly, because after startup, it informs me the version is `3.6.0`. I have tried installing using the `cargo` command you gave in the `README`. I have also tried downloading the source of the latest version `3.6.1` manually and installing locally from that; both produce the same result.

**Comment by LiquidityC** [comment]
You are absolutely right. I was in a hurry when releasing. I don't know a good way of solving this so I'll probably just push version 3.6.2 shortly. Thanks for the heads up.
