### ISSUE TITLE
Status height and input line misbehavior

### ISSUE THREAD

**Issue by dolandemort** [Blightmud/Blightmud#594]
If `blight.status_height()` is called while something is written in the input line, the text in the input line becomes invisible, and the cursor remains where it was. Typing something after that makes the text visible again.

**Comment by LiquidityC** [comment]
I can look into it. May I ask why it's being called when you're typing? It usually just a "call once at boot" type of config function.

**Comment by dolandemort** [comment]
In the mud I play, there is a summonable entity, and it isn't always present. When it is summoned, I have its status line above my always visible status line. Depending on circumstances (its death, unsummoning, not yet being summoned), the status height is changed between 1 and 2.

**Comment by dolandemort** [comment]
On the subject of this, it might be useful to people for the status API to include some function to allow us to check the current value of the status height, if it isn't too much trouble to implement.

**Comment by LiquidityC** [comment]
> On the subject of this, it might be useful to people for the status API to include some function to allow us to check the current value of the status height, if it isn't too much trouble to implement.

Drop an issue for this and I can take a look. I don't want features sneaking in within the scope of buggfixes :wink:
