### ISSUE TITLE
Setting to suppress "mud prompt line"

### ISSUE THREAD

**Issue by mikotaichou** [Blightmud/Blightmud#605]
Our mud uses a non-standard series of prompts because of how old it is and how many maintainers there are.  Would it be possible to get a toggle (setting) to suppress the functionality introduced from v3.0->v4.0?  As of now, our only option is to revert to 3.0 because the mud prompt line catches and displays nonsense.

Thanks!
-Miko

**Comment by mikotaichou** [comment]
swmud.org - for example, in panic files, the "more" block is saved as a prompt.  The "password:" block is saved as a prompt, but the real prompt isn't captured.  I had to write a new input listener to even pick up the prompt based on regex.

<img width="1500" alt="Screen Shot 2022-06-08 at 10 26 33 AM" src="https://user-images.githubusercontent.com/107127485/172641906-01a7e342-401e-44f2-a925-117e33c6b285.png">

In this screenshot "Password:" is from the login screen.

**Comment by mikotaichou** [comment]
It's more that we capture the prompt using lua and don't want it displayed.  It would be great to be able to disable the "mud prompt line" feature that was added.

**Comment by LiquidityC** [comment]
That's the bug. The prompt line is improperly respecting gags. I will submit a patch tonight.

I'm reluctant to keep the old solution because it was horrible to debug. Patched to the limit and not very stable.

**Comment by LiquidityC** [comment]
PR #606 should remedy your issues. SWmud does use GA so you're in a better position then many other muds. There is some details under `/help changes` that should help you out if your still not happy with the new handling.

Keep me posted if it helps or not.

**Comment by mikotaichou** [comment]
Thanks so much for the quick change! I validated on ubuntu 20.04 blightmud v4.0.0 hash rev 433712ee31e82ed65bf1ed5d1f1831212cb36ff9 and have the following results.  The change worked and correctly releases the remembered prompt on a new swmud prompt line.  SS below:

<img width="1499" alt="Screen Shot 2022-06-08 at 4 36 40 PM" src="https://user-images.githubusercontent.com/107127485/172712701-e15a575e-f361-4ed0-a169-c868f58dd6e6.png">

Would it be possible to get a toggle / setting to remove the empty space line if blank?  blightmud v3.6.3 rev d8093950a7d06f2dd83ea69e0ccaebedc4ca1a92 shown below:

<img width="1495" alt="Screen Shot 2022-06-08 at 4 44 21 PM" src="https://user-images.githubusercontent.com/107127485/172713863-1c5a2d9e-f39c-4034-abe8-959b59bab959.png">
