### ISSUE TITLE
Numpad/keypad key bindings

### ISSUE THREAD

**Issue by dolandemort** [Blightmud/Blightmud#608]
In TinyFugue, it was possible to use the numeric keypad as a way to easily navigate a mud by binding the directions to the number keys, e.g. 8 => north, 2 => s, 4 => w, 6 = e, and so on. I have been trying to accomplish the same in Blightmud, but it is turning out to be significantly more difficult.

In the `Bindings` help file, you state: we can bind escape sequences; and when these are unbound, Blightmud "will echo these commands to the output" to "make it easy for you to find the escape sequence you want to bind". This appears to only yield a useful output for the number pad 5 key (of course when numlock is toggled off), namely `\u{1b}[e`. All the other keys appear to already be bound, functioning as pageup/pagedown, home/end, previous input/next input, and so on.

How is one supposed to be able to find the escape sequences generated by these other keys? The escape sequences generated by the terminal using command `showkey -a` are of a different form, i.e. for number pad 5, `^[[E` results. Compare this with Blightmud's reported sequence for this same key, namely `\u{1b}[e`, and you can see the problem I am facing.

**Comment by LiquidityC** [comment]
I've done some reading on this. One thing that Blightmud should do which it doesn't do is put the numpad into application mode. Some terminals on the market seem to default to some version of this because I know there are players who navigate using numpad. However most do not.

The second thing which I can't control is the users choice of terminal emulator. Gnome terminal for one does not conform to proper VT100 standard. I have no knowledge of the alternatives. XTerm seems to be the gold standard when it comes to VT100 conformance.

In your case you could also rebind the keys on your numpad. Eg. Bind "up" to "north", "pageup" to "northeast" etc.

What terminal are you using?

**Comment by dolandemort** [comment]
I'm using Konsole, and the value it reports for `$TERM` is `xterm-256color`. In addition, the keybindings preset active in its settings is called `XFree 4`. There are three other keybindings presets: `Linux console`, `Solaris console`, and `macOS`. I have tried each of those other three, and none of them give a fully usable number pad within Blightmud, i.e. none of them give output for the escape sequence within Blightmud when each of the 9 numbers is pressed.

**Comment by LiquidityC** [comment]
Well, as mentioned before. Blightmud doesn't enable "application mode" on the numpad on boot. However is the numpad not working at all? Eg. Home, End, Left, Right, Up, Down, PgUp and PgDown aren't doing anything when pressed on the numpad?

**Comment by dolandemort** [comment]
The number pad seems to function as expected. When numlock is on, the number keys function as numbers. When numlock is off:
- 7 and 1 act as `home` and `end`.
- 8 and 2 act as `previous command history` and `next command history`.
- 9 and 3 act as `pageup` and `pagedown`.
- 5 generates an `Unknown command...` output with reported escape sequence `\u{1b}[e`.

Based on what you have said:
1. You say Blightmud doesn't enable "application mode", but is there any way to do so on my end?
2. How can I see, within Blightmud, what key generates what escape sequence?
3. You say some users have been able to utilize the number pad to bind navigation commands. Do you know what terminal they were using?

**Comment by LiquidityC** [comment]
I will submit a patch that enables "application mode" for the numpad this week. You can test with that and see if you get any different results.

**Comment by dolandemort** [comment]
Sounds great. Thanks for all the hard work you do.

Side question (and probably an outrageous one): What are your thoughts of making some kind of X11 type window wrapper for Blightmud in order to be able to intercept more extensively keyboard/button events?

**Comment by LiquidityC** [comment]
Sorry. This took for ever. Crunch at work followed by vacation. Here's a branch where application mode is enabled: https://github.com/Blightmud/Blightmud/tree/application_mode_enabled

**Comment by rchog** [comment]
> Sorry. This took for ever. Crunch at work followed by vacation. Here's a branch where application mode is enabled: https://github.com/Blightmud/Blightmud/tree/application_mode_enabled

Applying that change enables numpad bindings for me in appropriate terminal emulators, with the appropriate settings. Here's me pressing 123 and 1 on the numpad in **foot**, having done ```printf '\E[?1035l'``` to turn off numeric mode before launching Blightmud:
```lua
[**] Unknown command: "\u{1b}oq"
[**] Unknown command: "\u{1b}or"
[**] Unknown command: "\u{1b}os"
> /lua blight.bind("\u{1b}oq", function () blight.output("KP1 pressed") end)
KP1 pressed
``` 
Without the above change, I would just have '1231' on the input line. This works in **xterm** as well, and I believe it _should_ work in **urxvt** with the right settings. Some terminals, like **gnome-terminal** won't do it, no matter what in my experience.

Is there any chance of a command-line option or a setting that would toggle 
```rust
 204             write!(self.screen, "\x1b[?1035l").unwrap();                                                                                                           
 205             write!(self.screen, "\x1b=").unwrap();
```
at some point in the UI setup?
