### ISSUE TITLE
FR - Stripped down "direct connect" mode

### ISSUE THREAD

**Issue by ryanfantus** [Blightmud/Blightmud#628]
Describe the feature you would like added. Please be as detailed as possible.
Hi,

I am so glad this exists! My favorite MUD client for sure.

I have a request - how hard would it be to implement some sort of "direct connect" mode that shuts down once a user disconnects from a server?

The reason is that I would like to offer connecting to MUDs via Blightmud as a service, but I need to restrict access to things significantly. I don't want people to be able to change settings or anything, nor do I want them to be able to connect to something I don't spell out for them.

Use case:
User selects to connect to a certain game via a menu I provide externally. This launches Blightmud to connect to a specific server with an argument to mean it's launched in restricted mode. The user can't do anything in Blightmud aside from interact with the connected MUD. Once the user disconnects (by typing /quit or quitting directly in the MUD itself), Blightmud exits.

Is this possible? I would love this capability! Thanks.

**Comment by LiquidityC** [comment]
Should be doable through a script I think. `mud.on_disconnect()` combined with `blight.quit()` should let you quit on disconnect. As for settings.

Here is an example where a plugin disables existing aliases. You could most likely use something like this to get what you want.
Another alternative is just re-setting the settings file once blightmud has quit. That way the settings will be restored next time blightmud is started. That might be cleaner.

**Comment by ryanfantus** [comment]
Splendid! Thanks!

The quit on disconnect lua function works perfectly.

Is there any silver bullet way to just prevent someone from touching settings? Otherwise I'm happy to do the reset piece, just unsure exactly what the cleanest way to do so is.

Also, I'll follow up in Discord, thanks a ton for getting back to me so quick!
