### ISSUE TITLE
Buffer output becomes unreadable when recieving error from mud.

### ISSUE THREAD

**Issue by TrulyCold** [Blightmud/Blightmud#647]
**Describe the bug**
It appears like the character set is changed when the mud outputs an error log for debugging on the mud's end. Once this happens all further output in Blightmud is changed until Blightmud is closed (with CTRL+C) and reopened. The error persists if /dc is used to disconnect from the mud. Pressing CRTL+L will change the previously readable text before the error to unreadable in the buffer.

**To Reproduce**
Seems to happen every time the mud outputs its own error log.

**What terminal are you using?**
WSL Ubuntu in windows terminal app
Termux running proot-Ubuntu

**What mud were you playing?**
Sindome moo.sindome.org 5555

**Attachments**
[log1.txt](https://github.com/Blightmud/Blightmud/files/9387980/log1.txt)
![unknown](https://user-images.githubusercontent.com/110153593/185764996-9287bd86-b48c-4947-9e97-27e1d8089b60.png)

**Comment by TrulyCold** [comment]
I haven't encountered this issue in over a year. No idea if it is still relevant anymore. I want to say that it's safe to close unless others are still experiencing.

**Comment by LiquidityC** [comment]
Thanks for the feedback. I'll close for now.
