### ISSUE TITLE
Text-to-speech support on macOS?

### ISSUE THREAD

**Issue by TheQuinbox** [Blightmud/Blightmud#670]
Hi there,
Is Blightmud's text-to-speech functionality supported on the Mac? The readme mentions Speech Dispatcher (Linux only AFAIK). The Mac uses NSSpeechSynthesizer and AVSpeechSynthesizer for text-to-speech output, and I can't get it to build on Mac with text-to-speech support. Am I missing something?

**Comment by LiquidityC** [comment]
The supported backends are listed in the tts crates repo:

https://github.com/ndarilek/tts-rs

It does list AV foundation which I assume is one of those you mentioned above.

I, however, don't own a Mac so I've never been able to confirm or test this. In what way is your build failing?

If you want to help me figure this out I'd be very appreciative. We might even be able to create a tts Mac build in the CI release.
