### ISSUE TITLE
/connect requires "true" and "false" to be specified for tls and tls_verify options

### ISSUE THREAD

**Issue by ethindp** [Blightmud/Blightmud#671]
**Describe the bug**
Currently, connecting to a TLS-enabled server requires "true" and "false" to be specified to set/unset TLS-related options. I suspect that this is not the only place where this is necessary, but regardless it creates a rather unfriendly UX (since most people bar programmers wouldn't think about using "true" and "false", and so will try to connect to a TLS-enabled game and get no output followed by a sudden connection closure). 

**To Reproduce**
Try setting up any kind of server that uses TLS. Then, connect to the server, but after host and port, specify "on" and "off" (or any other value). You should get no output, even if output should be expected.

**What terminal are you using?**
I primarily use mate-terminal.

**What mud were you playing?**
Any TLS MUD will cause this problem to the unsuspecting user.

**Screenshots**
N/A

**Comment by LiquidityC** [comment]
What's the requested solution here. You want on/off to work as commands instead or in parallel of true/false?

**Comment by ethindp** [comment]
Yep, that exactly. Maybe we can add more affirmative/negative later.

**Comment by Xandaros** [comment]
There should also be an error message if you type in something invalid, instead of quietly assuming it to be "false"
