### ISSUE TITLE
Name lookup fails

### ISSUE THREAD

**Issue by yurigeinish** [Blightmud/Blightmud#672]
**Describe the bug**
```
/connect xxx yyy
```
leads to
```
[!!] failed to lookup address information: Temporary failure in name resolution
[!!] Failed to connect to xxx:yyy
```

I tried `starmourn.com 23`, or `google.com 80` or any address - the result is always immediate lookup failure.

- Blightmud is built with `cargo install --git https://github.com/blightmud/blightmud blightmud`
- `rustup show`: `rustc 1.64.0`
- Linux: Debian on WSL 2
- Build dependencies installed: `libasound2-dev`, `libssl-dev`, `pkg-config`

Outside of Blightmud, in the WSL 2 shell, name lookups work fine (all the same names that Blightmud fails to resolve) - via `ping`, or `nc`, or `curl`.

**To Reproduce**
Not sure.

**What terminal are you using?**
Windows Terminal.

**What mud were you playing?**
None.

**Screenshots**
N/A

**Comment by LiquidityC** [comment]
I can only give limited support on this. Partially because I don't have windows and partially because it's windows.

I'd recommend checking the repo out and testing if you get the same issues when running the following commands:

- `cargo run`
- `cargo run --release`
- `cargo install --path .`

**Comment by yurigeinish** [comment]
Oof, this is weird. I did:

1. `sudo apt install git`
2. `git clone ... && cargo run`
3. Now lookup works.
4. `cargo run --release` to see if it breaks in release mode
5. Lookup still working.
6. `~/.cargo/bin/blightmud` to see if the original binary is still broken
7. Lookup is working.
8. `sudo apt remove git && sudo apt autoremove` to see if the lookup behaviour was affected by the additionally installed packages
9. Lookup still working.

🤷‍♂️ I'm really at a loss here. Perhaps it really was a WSL fluke.

**Comment by LiquidityC** [comment]
There have been "very small" quirks with the `cargo install --git` command in the past. I don't know if it's to blame in this case. I'm going to close my eyes and ignore it for now and hope it never happens again.

I'm glad you got it working is all. Have fun mudding. :smile:
