### ISSUE TITLE
Mapper (Main issue)

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#69]
Based on some internet discussions I thought it would be fun to implement a mapper. Since I've never really used a client with those features this issue will be a tracking issue for needed features and functionality.
If you have requests or ideas for completeness of such features then please comment and I'll update the main description here.

- [ ] Mapper:
    - [x] Mapping when moving
    - [x] Detecting already mapped rooms (Coordinate system)
    - [x] Special exit support
    - [ ] Long exits (sometimes the distance between rooms isn't (1)
    - [ ] Room weights (for fastest path calculation)
    - [x] Saving and loading maps
- [ ] Pathfinding
- [ ] Path traversal with command delays and special exits
- [ ] Rendering (ascii map)

**Comment by Xandaros** [comment]
Many servers also send a room ID via GMCP and sometimes even exits and which rooms they lead to.
It should definitely be possible to manually add room information from Lua and disabling any auto-mapping functionality.

**Comment by LiquidityC** [comment]
Yes. I’ve put some work into this already. Essentially it will provide you with mapping functions and storage but it will be up to the user to adapt it through scripts to match his or her mud. So full user control is the goal.

**Comment by robg204** [comment]
Consider taking a look at the mudlet mapper, which is already implemented in lua.  I've taken quite a few handy lua functions from mudlets basic lua library and I use them successfully in my ~3000 line of blighty-lua that I've written to handle my game play on the muds I play.  I had started the project of porting their mapper over to blight (essentially just a matter of ripping out the qt elements), some blight provided windowing features would be great though.

**Comment by LiquidityC** [comment]
I have to agree with @robg204 on this one. Even though it's my code. For the time being the mapper idea is on hold over the summer. I'll rethink my ideas when I get back to it. Let's just say that the mapper is not set in stone. It was mostly just my curiosity that started it.

**Comment by mbsmith** [comment]
Just throwing in my two cents... as far as I know based on the mud clients i've worked on tintin++ seems to have the most comprehensive mapper out there.  It might be worth a look.

**Comment by LiquidityC** [comment]
Currently I have a working lua mapper when I play muds written completely in lua with saving etc. It will eventually be released as a plugin. Dropping this issue for now.

**Comment by SpyrosRoum** [comment]
> Currently I have a working lua mapper when I play muds written completely in lua with saving etc. It will eventually be released as a plugin. Dropping this issue for now.

Hi @LiquidityC, sorry for replying after so long. As far as I can tell that script is not posted anywhere. Can you upload it somewhere even if it's not 100% ready?

**Comment by LiquidityC** [comment]
@SpyrosRoum https://github.com/Blightmud/mapper

**Comment by Xandaros** [comment]
@SpyrosRoum If you're interested, I also created a mapper script a while ago, heavily based on TT++'s mapper. I'm actually quite happy with it.
I just published it: https://github.com/Xandaros/blightmud-mapper

It's not quite plug-and-play. Here's an excerpt of my main script that deals with the mapper:
```lua
local function update_map()
    local outp = MAPPER.curmap:ascii_string(MAPPER.colours)
    if MAPPER.on_print then
        MAPPER.on_print(outp)
    end
end

local function update_room(force)
    if MAPPER then
        if force or MAPPER.curmap:room().name == nil then
            MAPPER.curmap:room().name = msdp.get("ROOM_NAME")
        end
        MAPPER.curmap:room().terrain = tonumber(msdp.get("ROOM_TERRAIN"))
    end
    update_map()
end

local room_update_timer = nil
local function delayed_room_update()
    if room_update_timer then
        timer.remove(room_update_timer)
    end
    room_update_timer = timer.add(1, 1, update_room)
end

trigger.add("(\\+)", {}, function()
    if room_update_timer then
        timer.remove(room_update_timer)
        room_update_timer = timer.add(1, 1, update_room)
    end
end)

alias.add("#room update", function(_, _)
    update_room(true)
end)


local directions = {
    "n", "s", "e", "w",
    "ne", "se", "nw", "sw",
    "u", "d",
}

for _, direction in ipairs(directions) do
    alias.add("^" .. direction .. "$", function(_, line)
        mud.send(direction, {gag=true})

        MAPPER.curmap:checkpoint()
        MAPPER.curmap:dig(direction)
        MAPPER.curmap:move(direction)

        update_map()
        delayed_room_update()
    end)
end

timer.add(0.1, 1, function()
    msdp.on_ready(function()
        vars = {
            "CHARACTER_NAME",
            "LEVEL",
            "EXPERIENCE",
            "EXPERIENCE_MAX",
            "EXPERIENCE_MIN",
            "HEALTH",
            "HEALTH_MAX",
            "MANA",
            "MANA_MAX",
            "AFFECTS",
            "MONEY",
            "MOVEMENT",
            "MOVEMENT_MAX",
            "OPPONENT_LEVEL",
            "OPPONENT_HEALTH",
            "OPPONENT_HEALTH_MAX",
            "OPPONENT_NAME",
            "OPPONENT_STRENGTH",
            "AREA_NAME",
            "ROOM_NAME",
            "ROOM_TERRAIN",
            "WAIT_TIME",
            -- "ROOM_EXITS",
        }

        msdp.report(vars)

        for _, v in ipairs(vars) do
            msdp.register(v, update_bar)
        end
        msdp.register("AFFECTS", update_affects)
        msdp.register("ROOM_TERRAIN", delayed_room_update)
    end)

    MAPPER.on_print = function(outp)
        local file = io.open("windows/map", "wb")
        file:write(MAPPER.curmap:room().name or "")
        file:write("\n")
        for _, line in ipairs(outp) do
            file:write(line)
            file:write("\n")
        end
        file:close()
    end

    MAPPER.colours[1] = C_BBLACK -- City
    MAPPER.colours[3] = C_GREEN -- Forest
    MAPPER.colours[5] = C_BBLACK -- Cave?
    MAPPER.colours[6] = C_BBLUE -- Lake?
    MAPPER.colours[7] = C_BLUE -- River?
    MAPPER.colours[8] = C_BBLUE -- Underwater?
    MAPPER.colours[12] = C_BBLUE -- Ocean floor?
    MAPPER.colours[13] = C_BBLACK -- Cave?
end)
```

The MUD I play has no GMCP support or anything else to properly identify which room you are in, so a whole bunch of that is just updating the room names whenever it believes I'm in a new room. It doesn't always get it right.
I also have it write the map to a file which I show in a separate tmux pane. Obviously optional.

I've got a screencast of what it looks like, too. Not sure if that is the latest version, it's been a while: https://asciinema.org/a/3Iwf7QJodPKmGVKOZiXtmuchP
