### ISSUE TITLE
Warn users when Blightmud not compiled with TTS and using TTS

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#690]
Currently, starting Blightmud with `-T` when no TTS support is available will just silently fail. `tts.is_enabled()` will even return true, giving no indication that TTS is actually unavailable.

Here is what I would suggest if BM is compiled without TTS:
- Blightmud should refuse to start if the user is trying to start with `-T`, only printing an error
- The user should receive an error message when attempting to do `/tts on`
  - Actually, the `/tts` command as a whole should give some (text) feedback
- The user should receive an error the first time `tts.enable(true)` is called, but not more often to avoid spam
- `tts.is_enabled()` should always return false

**Comment by LiquidityC** [comment]
Agree on all points. I'm currently swamped with work but if anyone wants to pick this up it shouldn't be too difficult to get into.

**Comment by LiquidityC** [comment]
Once this is solved Blightmud will become 'noisy' when calling TTS when it's not available. Not functionally changed. Just a lot of error messages. Does that merit yet another major version or can we sneak that through silently?
