### ISSUE TITLE
Checksum Error when upgrading from 3.6.2 to 5.0.0

### ISSUE THREAD

**Issue by mirageglobe** [Blightmud/Blightmud#693]
**Describe the bug**
when using brew upgrade, the installer pulls the right version locally (5.0.0) in cache, however the checksum hash does not match

``` bash
==> Downloading https://github.com/Blightmud/Blightmud/releases/download/v5.0.0/blightmud-v5.0.0-macos.zip
Already downloaded: /Users/xxxxxxxx/Library/Caches/Homebrew/downloads/f1e532d786fa04af97799c0116d5dcae3d7b8d63d4d53d2e2976fc9109bf3a96--blightmud-v5.0.0-macos.zip
Error: SHA256 mismatch
Expected: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
  Actual: 5f49ee4c58c8528a08d70b989b888996f6ba8aca8f061a034754043dd6c685a7
    File: /Users/xxxxxxxxx/Library/Caches/Homebrew/downloads/f1e532d786fa04af97799c0116d5dcae3d7b8d63d4d53d2e2976fc9109bf3a96--blightmud-v5.0.0-macos.zip
To retry an incomplete download, remove the file above.
```

**To Reproduce**
on macos X montery with the built-in terminal, run `brew upgrade blightmud`

**What terminal are you using?**
apple terminal v 2.12.7

**What mud were you playing?**
n/a

**Screenshots**
n/a

**Comment by LiquidityC** [comment]
I've updated the formula. You can try again now.

**Comment by mirageglobe** [comment]
how did the older brew tap work?

**Comment by LiquidityC** [comment]
The older brew tap? Not sure what you are asking for. And I don't own a Mac so I know very little about the brew package manager.

**Comment by mirageglobe** [comment]
aha. sorry we posted at the same time (about the same time).. it works now. thanks!

**Comment by mirageglobe** [comment]
> 

was interested in where the formula folder was. it seems like dxxxx91 was maintaining the mac homebrew version?

**Comment by LiquidityC** [comment]
He help me set it up but from that point I've been doing the releases.

**Comment by mirageglobe** [comment]
thanks @LiquidityC ! confirm that all works fine now. cheers for the superfast response.
