### ISSUE TITLE
Create input prompt highlighting capabilities

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#723]
## Description

To facilitate a spellchecker there needs to be a possibility of colorizing the input prompt content.

This should be solved by introducing a **InputPromptMask** (name isn't set in stone). This should be a struct containing ANSI escapes and indexes. Before the prompt input is rendered in the UI we should merge the prompt content with the **InputPromptMask** to create colorized output.

This way typed text and color codes don't mix which should be easier to handle. 

## Steps

- Introduce the **InputPromptMask** (mask) (choose a better name if you can think of one?)
- Merge input prompt text with the **mask** before rendering to screen
- Create lua api allowing scripts to create these **masks**
- Write tests and stuff

**Comment by cpu** [comment]
> Introduce the InputPromptMask (mask) (choose a better name if you can think of one?)

Are you imagining this would slot in to replace the `strbuf` and `buffer` fields of the `CommandBuffer` struct? https://github.com/Blightmud/Blightmud/blob/ea3b6bfcbc927abe8d3aea8abe40f737a6609ea8/src/ui/command.rs#L48-L50

**Comment by LiquidityC** [comment]
I haven't looked into it in any depth yet. First thought looking at it now is that we add a field which will be the mask inside the command buffer. But I haven't checked if we can reach that from lua yet.
