### ISSUE TITLE
Implement a spellchecker

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#725]
## Description

To allow spellchecking in Blightmud we'll need to implement it.

## Steps

- Create a spellchecker for user input (input prompt) in lua
- Utilize the highlighting functionality introduced in #723
- Utilize spellchecking api introduced in #724

**Comment by cpu** [comment]
One aspect that might need some thought is how users will provide dictionary data and whether they need to source the data themselves or if it'll be bundled somehow. 

In the Hunspell case (assuming that's what library #724 ends up using) the code will need to provide paths to both an affix file and a dictionary file. I found https://github.com/wooorm/dictionaries when I was looking around briefly. In my initial testing I followed the example from the [Hunspell README](https://github.com/hunspell/hunspell#usage) and `wget`'d the OpenOffice en_US files to reference.

**Comment by LiquidityC** [comment]
Anything GPL, MIT or Apache2 licensed should work here. I definitely think these files should be provided by lua through the lua bindings we build. It's best if users can change languages and provide their own dictionaries if they want to.

**Comment by cpu** [comment]
I put up a WIP PR with the Spellchecking API for: https://github.com/Blightmud/Blightmud/pull/736

Concurrent with that, I built a spellchecker plugin to resolve this issue: https://github.com/cpu/blightspell

If you'd rather this be built-in to Blightmud I'm open to that but it felt better to build this separately as a plugin that we can iterate on faster than the Blightmud release schedule. LMK what you think.

The basic user experience is already pretty good. I think I can make it better still if https://github.com/Blightmud/Blightmud/issues/737 is also implemented.
