### ISSUE TITLE
Failing to start up in mac osx big sur 11.7.4

### ISSUE THREAD

**Issue by mirageglobe** [Blightmud/Blightmud#768]
**Describe the bug**
Bit of a stretch but i just tested blight on an old mac running big sur. Getting this issue. might be some incompatible symbol used? Its only happened after recent upgrade from 5.0 to 5.1.

``` bash
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /usr/local/bin/blightmud (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /usr/local/bin/blightmud
Abort trap: 6
```

**To Reproduce**
install on mac osx big sur 11.7.4 via brew and run blightmud

**What terminal are you using?**
tested on default terminal

**What mud were you playing?**
n/a

**Screenshots**
<img width="577" alt="image" src="https://user-images.githubusercontent.com/577792/227699830-fac37c7b-6d2b-4c51-b67d-67c47a6e49f6.png">

**Comment by LiquidityC** [comment]
What version number does "Big Sur" have?
Looks like a libc mismatch. We are a bit limited on how many versions of each OS that we can release for. 

Do you get the same problem if you build from source?

**Comment by mirageglobe** [comment]
hi LiquidityC! thanks for the super fast response.

current big sur is 11.7.4. which is the last stable version of big sur. perhaps consider compiling for one of the latest for each major release? seems like macs are released to support about two years (i.e. 2013 macs can only upgrade to big sur max. 2015 and so on.) so its more of a hardware limitation that prevents official upgrades.

12.6.3 montery (latest for that major release)
13.2.1 ventura (current latest)

**Comment by mirageglobe** [comment]
yep local build works. anyway I can help release this if it helps?

**Comment by LiquidityC** [comment]
The releases are automated through GitHub CI. I'll check what we have available and also read up on what handling bee offers for these cases. If it all fits then I'm fine with extending the tap and the release builds. 

If it doesn't then I'm afraid out of service macos releases will have to rely on compiling.

If anyone is good with brew. Is it possible to make a brew thing that compiles instead of downloading a binary? That seems like a first step no matter how this issue is tackled later on.

**Comment by mirageglobe** [comment]
the github ci actions (i am somewhat familiar) - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners allows both `macos-latest` as well as `macos-11` runners. I assume you are using github CI runners to build it?

**Comment by mirageglobe** [comment]
perhaps one way is in your .github/workflows

```
 build_macos_11:
    name: Build for macOS big sur
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
... make sure output is another prefixed-release?
```

**Comment by mirageglobe** [comment]
if opting the build local route. theres an example here which is close : https://github.com/Homebrew/homebrew-core/blob/92dda2bfa4e4e40c94564fe1e46018efc3d57e26/Formula/choose-rust.rb

```
class mycustombrew < Formula
...
  bottle do
    rebuild 1
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "aaaaabbbbb-sha"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "aaaaabbbbb-sha"
    sha256 cellar: :any_skip_relocation, ventura:        "aaaaabbbbb-sha"
    sha256 cellar: :any_skip_relocation, big_sur:        "aaaaabbbbb-sha"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "aaaaabbbbb-sha"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "build", *std_cargo_args
  end
...
end
```

**Comment by LiquidityC** [comment]
@mirageglobe I don't own a Mac. If i fix the CI to build for Mac 11 and 12 with different suffixes. Can you help me out with our tap: [#Blightmud/homebrew-blightmud ](https://github.com/Blightmud/homebrew-blightmud)?

The big issue is that I can't test it.

**Comment by mirageglobe** [comment]
yep sounds good. we are doing the different builds via CI for now yep?

**Comment by mirageglobe** [comment]
i spent some time looking and think this is what would be suitable : https://github.com/dandavison/delta/blob/master/HomeBrewFormula/git-delta.rb 

i just cant figure out how to get the mac version number to compare

**Comment by LiquidityC** [comment]
I'm closing this as we have the builds ready. Next step is to update homebrew which will be solved by this: https://github.com/Blightmud/homebrew-blightmud/pull/4
