### ISSUE TITLE
Replace or remove actions-rs dependency in rust.yml CI action

### ISSUE THREAD

**Issue by LiquidityC** [Blightmud/Blightmud#799]
[actions-rs/toolchain](https://github.com/actions-rs/toolchain) seems to be unmaintained. There are some warnings about it using **set-option** when the builds are running.
We can either drop it and just manually call `rustup` and `cargo install <stuff>` or switch to a maintained alternative. I don't really care how we do it.

**Comment by cpu** [comment]
I switched some other projects that were using `actions-rs/toolchain` to https://github.com/dtolnay/rust-toolchain. The author is a maintainer of `serde` and several other popular crates. I can do the work if nobody beats me to it (it'll be later tonight/tomorrow at the earliest).
