### ISSUE TITLE
Plugins in Rust

### ISSUE THREAD

**Issue by dangardner** [Blightmud/Blightmud#906]
Since interpreted Lua is slow compared with compiled Rust, is there any interest in implementing a Rust-based plugin system for Blightmud?

I'm imagining extending the existing plugin system to be aware of a main.rs where it would expect main.lua and adding a cargo build step after download. If this would be of interest, do you have any thoughts on a preferred plugin design, e.g. using abi_stable or wasm?

**Comment by cpu** [comment]
> Since interpreted Lua is slow compared with compiled Rust, is there any interest in implementing a Rust-based plugin system for Blightmud?

Do you have examples of plugins you would write in Rust that can't be effectively realized in Lua? Personally I'm a little bit skeptical that the complexity of a plugin system is justified. Not to say that I'm strictly opposed, just that I need more convincing :-)

**Comment by cpu** [comment]
I think we can close this for now and say that interest is blocked on an understanding of what capabilities are needed and why they can't be expressed in Lua.

Thanks!
