### ISSUE TITLE
Duplicate or missing triggers when loading scripts

### ISSUE THREAD

**Issue by jhall11** [Blightmud/Blightmud#935]
**Describe the bug**
When loading Blightmud, or reloading scripts using the method in `config_scripts.md` maybe 10% of the time I will have either triggers duplicated or GMCP callbacks not register. I see no error messages when this occurs and besides the unusual behavior everything looks to be loaded correctly. I am printing a loading message at the top of my script file and that has only been printed once when the issue occurs. I have not yet been able to reproduce with -V logging option enabled.

**To Reproduce**
load/reload scripts
Scripts are located in ~/.config/blightmud/
I have config.lua which is from config_scripts.md and another lua file which has all my triggers and gmcp stuff for the mud

**What terminal are you using?**
Windows Terminal, running Ubuntu 22.04 on WSL

**Comment by LiquidityC** [comment]
Could you attach your script files and also show in what folders they are located?

**Comment by jhall11** [comment]
I think I've figured out what was happening, looks like it was caused by an incomplete attempt to split my script into smaller files. In the `config.lua` script I have an `on_connect` function that loads the main mud script which is in the `config_dir`. But I forgot that files in  the `config_dir` also get loaded, so I was loading my main script twice once on load/reload and once on connection to the mud. I can consistently reproduce the duplicate triggers getting registered when connecting to a mud. I think the inconsistency was sometimes I would reload scripts then reconnect vs just reload. I have not been able to reproduce the gmcp callback issue, but I suspect that is probably a similar issue.

**Comment by LiquidityC** [comment]
Easy mistake to make. I was suspecting it might be something like this. Would have surprised me if a bug like this had been flying under the radar for such a long time. It's still helpful with issues reports so thanks for taking the time.

If you don't feel there's anything left to solve you can close this.
