### ISSUE TITLE
Question on scripting.

### ISSUE THREAD

**Issue by YaroKasear** [Blightmud/Blightmud#961]
What is your question?

I would really like to switch to this client, but right now the one thing stopping me from ditching TinyFugue for this is that it has no built-in character/password management. I saw an issue asking about this that got a "would be nice if someone made a plugin for this!" with no information or response on if anyone actually implemented an actual plugin for characters. 

It definitely won't be convenient to have to look up each character and password manually to use this client when all other clients out there already implement this rather basic feature. 

So I thought I would try to implement some rudimentary character implementations based on the config_script documentation, except it doesn't provide a whole lot of documentation on a few things that would actually make per-character stuff possible.

So, three questions.

1. Did anyone actually implement this script? If so, where can I find it?
2. Is there a way to get the command line used to invoke blightmud in a script? So that I can, for example, add my own command line arguments and thus make it possible for me to specify a server and character when I start blightmud?
3. If not, is there a way to get lua to tell me what server (from servers.ron) I connected to so I can use that to identify a character? I see again in the config_script documentation apparently blightmud does put some variables in the session store, but nowhere in the documentation is there a list of what variables blightmud already puts there, and the storage documentation simply tells you how to add and remove variables, which is only half the information I'd need.

Bonus: I like that you have a Nix flake. Would be neat if you fleshed that out and made a nix module for home-manager wherein someone could put servers and have that configuration put there in the Nix store. And it would be nice if blightmud simply implemented what I would have thought was a basic feature in character management.

**Comment by cpu** [comment]
I think there are ergonomics improvements to be made in this area. There have been other folks asking similar questions in the Discord. Pulling out concrete feature requests from this more general discussion issue would be helpful.

> Is there a way to get the command line used to invoke blightmud in a script? So that I can, for example, add my own command line arguments and thus make it possible for me to specify a server and character when I start blightmud?

I don't believe this is possible today. You can however access environment variables from Lua using `os.getenv`, so this might be an acceptable workaround in the shortterm. 

> If not, is there a way to get lua to tell me what server (from servers.ron) I connected to so I can use that to identify a character? 

I think it makes sense to augment the [`mud.on_connect`](https://github.com/Blightmud/Blightmud/blob/dev/resources/help/mud.md) callback to additionally receive the servername but it isn't something implemented today.

> Bonus: I like that you have a Nix flake. Would be neat if you fleshed that out and made a nix module for home-manager wherein someone could put servers and have that configuration put there in the Nix store. 

Pull requests welcome :-)

**Comment by YaroKasear** [comment]
> I think there are ergonomics improvements to be made in this area. There have been other folks asking similar questions in the Discord. Pulling out concrete feature requests from this more general discussion issue would be helpful.
> 

I'll see about making one as I progress, possibly. Ideally, this would be maybe something we could put in the server.ron file, maybe a list in each server's entry of character and password... and we could put together the usual "MUD type" stuff for autoconnect commands. Just a thought. I'll do a formal feature request when I get back around to this in my Nix stuff.

> > Is there a way to get the command line used to invoke blightmud in a script? So that I can, for example, add my own command line arguments and thus make it possible for me to specify a server and character when I start blightmud?
> 
> I don't believe this is possible today. You can however access environment variables from Lua using `os.getenv`, so this might be an acceptable workaround in the shortterm.
> 

This is useful. Though as you say, probably best considered a workaround and not the "official" way to pull this off.

> > If not, is there a way to get lua to tell me what server (from servers.ron) I connected to so I can use that to identify a character?
> 
> I think it makes sense to augment the [`mud.on_connect`](https://github.com/Blightmud/Blightmud/blob/dev/resources/help/mud.md) callback to additionally receive the servername but it isn't something implemented today.
> 

If I knew any Rust or Lua I'd consider trying my hand at this. I think it'd be a good idea for the Lua environment to provide a fairly complete picture to a script's author of its full state.

> > Bonus: I like that you have a Nix flake. Would be neat if you fleshed that out and made a nix module for home-manager wherein someone could put servers and have that configuration put there in the Nix store.
> 
> Pull requests welcome :-)

I'm taking on something a little simpler first: A tinyfugue module. A .tfrc is a rather simpler format than server.ron or lua scripts which this solution would entail. I figure once I actually figure out how to make dotfiles with home-manager first I'll have the know-how to tackle blightmud's configs.

**Comment by Xandaros** [comment]
Somebody else also requested the servername be included in `on_connect` on the Discord, which I thought was a pretty good idea, but @LiquidityC thought using environment variables would be the simpler option.

As for credentials, I personally have a `credentials.lua` Lua file that looks something like this:
```lua
return {
    ["hostname"] = {
        username = "asdf",
        password = "fghj"
    },
    ...
}
```

Which is then loaded and accessed to get the login credentials for the server I am connecting to. This particular way only works if you only use one character per MUD, obviously.

A more central system might be a good idea, but I think the biggest challenge is going to be interfacing with the MUD. Some allow login with GMCP, some don't.
For those that don't, they will have different login prompts. How is a central system to know when to send username and password?
We can assume that it's the first two things that need to be sent, but some MUDs have a menu first, where you select between logging in or creating a new character. (Though, granted, those seem rare. Typically it's a special username to create a new char)

I suppose we could include a regex for username and password prompts as part of the configuration, but... ugh
Similarly, we can just assume it's the first two things to be sent, and it just won't work for the few MUDs that do it differently, but... still not great.

How do other clients handle this?

**Comment by YaroKasear** [comment]
> Somebody else also requested the servername be included in `on_connect` on the Discord, which I thought was a pretty good idea, but @LiquidityC thought using environment variables would be the simpler option.
> 
> As for credentials, I personally have a `credentials.lua` Lua file that looks something like this:
> 
> ```lua
> return {
>     ["hostname"] = {
>         username = "asdf",
>         password = "fghj"
>     },
>     ...
> }
> ```
> 
> Which is then loaded and accessed to get the login credentials for the server I am connecting to. This particular way only works if you only use one character per MUD, obviously.
> 

Unfortunately I would have many alts on a few servers. Would have been perfect otherwise. 

> A more central system might be a good idea, but I think the biggest challenge is going to be interfacing with the MUD. Some allow login with GMCP, some don't. For those that don't, they will have different login prompts. How is a central system to know when to send username and password? We can assume that it's the first two things that need to be sent, but some MUDs have a menu first, where you select between logging in or creating a new character. (Though, granted, those seem rare. Typically it's a special username to create a new char)
> 
> I suppose we could include a regex for username and password prompts as part of the configuration, but... ugh Similarly, we can just assume it's the first two things to be sent, and it just won't work for the few MUDs that do it differently, but... still not great.
> 
> How do other clients handle this?

While I've never authored my own client before, from what I understand, most servers will send strings to signal to the client if they use protocols like MCCP so the client can turn on those features and send a response signalling the server they turned them on. 

If I or anyone is to implement this, I'd suggest maybe looking at other open source clients:

Tinyfugue doesn't really do multiple characters per world, but since it supports a character per world, a user can easily do multiple characters per world by simply making a world per character. Something like this in a .tfrc:

/addword -Ttiny worldname.charactername1 charactername1 password host 1234
/addword -Ttiny worldname.charactername2 charactername2 password host 1234

Tinyfugue doesn't support spaces in world names, so my chosen format is world.char.

The -T is used to specify the kind of server connected to and Tinyfugue even enables the user to define new server types. It's mostly so the server knows what login commands to use.

Then in the shell, it's just a matter of `tf worldname.charactername1` and it fires up on the server with that character. If Blightmud simply allowed for identifying the name of the world passed using the -w switch, then that would pretty much cover this feature.

Alternatively, if you want to be complete, check out Kildclient, which will do world files which include lists of characters and passwords for them. That'd probably be more complex to implement but it could eliminate reduntantly declaring the same server over and over again for each character.

**Comment by LiquidityC** [comment]
I see the practical value in storing characters and passwords "on" servers but I'm still not convinced that it's a feature that Blightmud should "own".  Different users will prefer different solutions regarding this and as mentioned above, different muds login differently. And I'd like to avoid being the maintainer of the universal "login to everything" solution.

I'm also not a fan of taking responsibility for reversible password storage. I'd prefer that the users chose how they deal with that.

In the case of starting and connecting to a world with different characters I'd still argue that environment variables is a readily available and clean option. Eg. `CHAR=charname PWD=password blightmud -w mymud`. This can be easily extended with your favorite password manager. Eg. `CHAR=charname PWD=$(bw get password hashkey) blightmud -w mymud`.

These environment variables can be easily read within lua in the `on_connect` callback.

If one is more inclined to be able to connect from within blightmud then a custom extension of the `/connect` command or perhaps something related to world is quite easy to setup for personal needs and if there is a more general demand I'd still suggest that this be added as a plugin.

Blightmud does expose everything needed to make such a plugin and the plugin in turn does not need to be tied to Blightmud releases and would be free to patch and create new releases on its own schedule.

If someone was to create such a plugin I would gladly reference it in Blightmud documentation etc.

As for the case of including server name as an optional third parameter to the "on_connect" command. I don't see a problem with that other then it possibly being redundant due to the environment variable options mentioned above. So if someone wants to take a look at that. Go ahead. I'm too busy with work at the moment and I think there are some caveats but anything is possible. :wink:

**Comment by cpu** [comment]
FWIW I definitely agree that auto login is best handled as a plugin :+1: I'm open to trying to implement ideas that would make writing that sort of plugin easier, as time permits.

In the short term I have some other irons in the fire I want to take care of before I start on anything new so I'd say if someone is especially keen for progress to be made here it sounds like they'll have to roll up their sleeves and write some code.

**Comment by YaroKasear** [comment]
This is all fair. My only point of criticism (And I mean it as very light.) is pointing out that to date this is the only MUD client I've seen that doesn't have this as a feature. 

It is definitely a concern to store passwords in cleartext, fortunately one advantage to the plugin approach is I could write something that would work with external tools (e.g. sops-nix for Nix users, etc.). 

Environment variables are good, but even just a slight expansion on the capabilities of the lua scripting would likely be better. At the very least a way to identify the world name (If any.) and not just the host of what you're connecting to. Environment variables can cover this, but since world names are already a part of Blightmud as a feature regardless of what I'm discussing here, it makes sense to still expose that to scripts for other purposes we might not even think of. 

At any rate, my question was already answered! Thanks for the conversation. I'll close this now.

**Comment by cpu** [comment]
>  My only point of criticism (And I mean it as very light.) is pointing out that to date this is the only MUD client I've seen that doesn't have this as a feature.

It's fair criticism and I don't think anyone disputes that it's an important feature for many folks. I think having a solution for this is a need someone will fill for Blightmud sooner or later.

> Environment variables are good, but even just a slight expansion on the capabilities of the lua scripting would likely be better. At the very least a way to identify the world name (If any.) and not just the host of what you're connecting to.

The consensus on this idea in this thread seems positive to me, there's just nobody with the time to immediately implement it. I've opened a separate ticket we can keep open for this: https://github.com/Blightmud/Blightmud/issues/963 

If you try writing a plugin for your character management needs and find additional gaps or room for improvement please file issues with ideas.
