### ISSUE TITLE
Crashes on a Tektronix 4010 emulator (tek4010)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Blightmud/Blightmud#967]
**Describe the bug**
I decided to have some fun and wanted to do it with an era appropriate feel. So I started it alongside a Tektronix 4010 emulator. However, Blightmud freaks out and crashes apon starting alongside tek4010.

**To Reproduce**
Run alongside tek4010.
`./tek4010 -noexit blightmud`

**What terminal are you using?**
WSL1 - Windows Command Prompt
XLaunch for X11 support
tek4010 (Tektronix 4010 emulator)

**What mud were you playing?**
N/A (Can't even connect to begin with.)

**Screenshots**
Get ready for 1972.
![image](https://github.com/Blightmud/Blightmud/assets/61162037/417e51c2-8d44-40c3-84a3-84962fe53d1c)

**Comment by LiquidityC** [comment]
Can you attach the crash log?

**Comment by TheSystemGuy1337** [comment]
[report-f4d45de3-61d8-451c-a257-d6ce7468e4ee.log](https://github.com/Blightmud/Blightmud/files/13772594/report-f4d45de3-61d8-451c-a257-d6ce7468e4ee.log)

**Comment by Xandaros** [comment]
Probably the same issue as https://github.com/Blightmud/Blightmud/issues/833

The emulator probably doesn't create a proper virtual terminal, just redirecting the streams. Blightmud doesn't like that.

**Comment by TheSystemGuy1337** [comment]
> Probably the same issue as #833
> 
> The emulator probably doesn't create a proper virtual terminal, just redirecting the streams. Blightmud doesn't like that.

I will therefore cheat, and create a Linux VM in VirtualBox, SSH into it and run Blightmud from there.

**Comment by TheSystemGuy1337** [comment]
Tried it on a Ubuntu VM. No difference.

**Comment by LiquidityC** [comment]
What shell is the Ubuntu VM running and how did you start BM within it? Did you get the same crash log?

**Comment by TheSystemGuy1337** [comment]
I have no idea what windowing environment it is using, but I am on Ubuntu 23.10 in the VM. It could be Wayland, it could be X11.

I started BM like this:` ./tek4010 -noexit blightmud`

The logs are identical. I guess Blightmud really does not like having the streams be redirected. SSH and links2 work in tek4010 just fine, so this is a compatibility problem.


```
name = "blightmud"
operating_system = "Ubuntu 23.10 (mantic) [64-bit]"
crate_version = "5.3.0"
explanation = """
Panic occurred in file 'src/main.rs' at line 85
"""
cause = "Panic: Inappropriate ioctl for device (os error 25)"
method = "Panic"
backtrace = """

   0: 0x55978c69ca3b - <unresolved>
   1: 0x55978c69cfb3 - <unresolved>
   2: 0x55978c69cfc9 - <unresolved>
   3: 0x55978cdffe1b - <unresolved>
   4: 0x55978c69cb45 - <unresolved>
   5: 0x7fbc80e280d0 - __libc_start_call_main
                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   6: 0x7fbc80e28189 - __libc_start_main_impl
                at ./csu/../csu/libc-start.c:360
   7: 0x55978c6997e5 - <unresolved>
   8:        0x0 - <unresolved>"""
```
I think the best solution is to [intergate Tek4010 within Blightmud to work around these issues](https://github.com/rricharz/Tek4010)

**Comment by LiquidityC** [comment]
I see. You just changed the host environment. The problem is most likely still that the tek4010 emulator doesn't provide a full TTY then. Whatever you are running blightmud in must provide a vt100 compatible TTY.

**Comment by TheSystemGuy1337** [comment]
Therefore, there is no point continuing to try and fix this. It's a compatibility problem. Case closed.
